Repository mozilla-mobile/focus-ios, pull requests merged in 2021-08, with the labels that each got.

#2086 l10n-follow-up-5-missing-arguments-init
  taskcluster/focusios_taskgraph/__init__.py
Labels: Needs Landing

#2087 L10n update snapshot helper to run fastlane
  ScreenshotTests/SnapshotHelper.swift
Labels: Needs Landing (Squash)

#2068 Fixes #2056 - Include the String Tools into the Focus project
  tools/Localizations/.gitignore
  tools/Localizations/Package.resolved
  tools/Localizations/Package.swift
  tools/Localizations/README.md
  tools/Localizations/Sources/Localizations/CreateTemplatesTask.swift
  tools/Localizations/Sources/Localizations/ExportTask.swift
  tools/Localizations/Sources/Localizations/ImportTask.swift
  tools/Localizations/Sources/Localizations/main.swift
  tools/Localizations/Tests/LocalizationsTests/LocalizationsTests.swift
Labels: Needs Landing (Squash)

#2063 Fixes #1953 - Browser - Redesign of autocomplete opt-in
  Blockzilla/Colors.xcassets/PrimaryDark.colorset/Contents.json
  Blockzilla/OverlayView.swift
  Blockzilla/SearchSuggestionsPromptView.swift
  Blockzilla/UIColorExtensions.swift
  Blockzilla/UIConstants.swift
  XCUITest/PastenGoTest.swift
  XCUITest/WebsiteAccessTest.swift
Labels: Needs Landing (Squash)

#2090 l10n - Add cache step to L10nBuild
  bitrise.yml
Labels: Needs Landing (Squash)

#2095 Fixes #1919 - Disable the link to What's new (menu item)
  Blockzilla/BrowserViewController.swift
  Blockzilla/SettingsViewController.swift
Labels: Needs Landing (Squash)

#2066 Fixes #2065 - Remove old l10n tooling and documentation
  import-locales
  import-locales.go
  import-locales.sh
Labels: Needs Landing (Squash)

#2097 Fixes #2096 - String export omits trailing newline
  tools/Localizations/Sources/Localizations/ExportTask.swift
Labels: Needs Landing (Squash)

#2088 Fixes #2038 Dismiss url bar button is stretched
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#2073 For #2067 - Create test plan for refresh branch
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/xcshareddata/xcschemes/Focus.xcscheme
  SmokeTestRefresh.xctestplan
  bitrise.yml
Labels: Needs Landing (Squash)

#2111 l10n-follow-up-6-wait-for-bitrise-api-response
  taskcluster/scripts/bitrise-schedule.py
Labels: Needs Landing (Squash)

#2108 Improve slack notifications - show executed test plan on error
  bitrise.yml
Labels: Needs Landing

#2110 Fixes #1956 - Shield Data - Visual Redesign
  Blockzilla/BrowserViewController.swift
  Blockzilla/Colors.xcassets/PrimaryBackground.colorset/Contents.json
  Blockzilla/Colors.xcassets/SecondaryBackground.colorset/Contents.json
  Blockzilla/TrackingProtectionViewController.swift
  Blockzilla/UIColorExtensions.swift
  Blockzilla/UIConstants.swift
  Blockzilla/en.lproj/Localizable.strings
  Shared/Settings.swift
Labels: Needs Landing (Squash)

#2120 Fixes #1920 Opening favorites site via Siri Shortcuts is broken on iPhone
  Blockzilla/AppDelegate.swift
Labels: Needs Landing (Squash)

#2112 l10n-follow-up-7-bitrise-workaround-for-fastlane-issue
  bitrise.yml
Labels: Needs Landing

#2124 l10n-follow-up-8-fix-download-derived-data-path
  bitrise.yml
Labels: Needs Landing (Squash)

#2123 Fixes #2122 - Import Latvian (lv) and Lithuanian (lt) strings
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/lt.lproj/InfoPlist.strings
  Blockzilla/lt.lproj/Intents.strings
  Blockzilla/lt.lproj/Intro.strings
  Blockzilla/lt.lproj/Localizable.strings
  Blockzilla/lv.lproj/InfoPlist.strings
  Blockzilla/lv.lproj/Intents.strings
  Blockzilla/lv.lproj/Intro.strings
  Blockzilla/lv.lproj/Localizable.strings
  ContentBlocker/lt.lproj/InfoPlist.strings
  ContentBlocker/lv.lproj/InfoPlist.strings
  ScreenshotTests/lt.lproj/InfoPlist.strings
  ScreenshotTests/lv.lproj/InfoPlist.strings
  XCUITest/lt.lproj/InfoPlist.strings
  XCUITest/lv.lproj/InfoPlist.strings
  tools/Localizations/Sources/Localizations/ExportTask.swift
Labels: Needs Landing (Squash)

#2133 Fixes #2131 - Create scripts to automate string import/export
  tools/export-strings.sh
  tools/import-strings.sh
Labels: Needs Landing (Squash)

#2135 Fixes #2134 - Update strings for refreshed Shield Data screen
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#2109 For #2067 - Create test plan for refresh branch (#2073)
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/xcshareddata/xcschemes/Focus.xcscheme
  Blockzilla.xcodeproj/xcshareddata/xcschemes/Klar.xcscheme
  SmokeTestRefresh.xctestplan
  bitrise.yml
Labels: Needs Landing (Squash)

#2141 Fixes #2130 - Update Bitrise steps to more recent versions
  bitrise.yml
Labels: Needs Landing (Squash)

#2136 Fixes #2118 - Export the Blockzilla/en.lproj/Intents.strings
  Blockzilla/Intents.intentdefinition
  Blockzilla/SiriShortcuts.swift
  Blockzilla/en.lproj/Intents.strings
  tools/Localizations/Sources/Localizations/ExportTask.swift
Labels: Needs Landing (Squash)

#2148 Fixes #2147 - Update provisioning profiles
  Blockzilla.xcodeproj/project.pbxproj
Labels: Needs Landing (Squash)

#2138 Fixes #2043 - Search suggestions trimmed characters
  Blockzilla/OverlayView.swift
  Blockzilla/StringExtensions.swift
Labels: Needs Landing (Squash)

#2132 Fixes #1961 - iPad - URL bar redesign
  Blockzilla/BrowserViewController.swift
  Blockzilla/UIConstants.swift
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#2155 Fixes #2154 - Strings Update
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/UIConstants.swift
  XCUITest/SettingAppearanceTest.swift
Labels: Needs Landing (Squash)

#2157 Fixes #2156 - Tips Update
  Blockzilla/AppDelegate.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/HomeView.swift
  Blockzilla/TipManager.swift
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#2163 Fixes #2161 - Show the home screen tips for all English locales
  Blockzilla/TipManager.swift
Labels: Needs Landing (Squash)

#2167 Fixes #2168 - Include Hebrew in shipping_locales.txt
  shipping_locales.txt
Labels: Needs Landing (Squash), Needs Uplift

#2164 Fixes #2160 - Add a home screen tip about shortcuts
  Blockzilla/AppDelegate.swift
  Blockzilla/TipManager.swift
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#2151 Fixes #1954 - Settings - Modern iOS Settings Layout
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/AboutViewController.swift
  Blockzilla/AddCustomDomainViewController.swift
  Blockzilla/AddSearchEngineViewController.swift
  Blockzilla/AutocompleteCustomUrlViewController.swift
  Blockzilla/AutocompleteSettingViewController.swift
  Blockzilla/SafariInstructionsViewController.swift
  Blockzilla/SearchSettingsViewController.swift
  Blockzilla/SettingsContentViewController.swift
  Blockzilla/SettingsViewController.swift
  Blockzilla/SiriFavoriteViewController.swift
  Blockzilla/TrackingProtectionViewController.swift
  Blockzilla/UIConstants.swift
  Blockzilla/UITableViewCellExtensions.swift
Labels: Needs Landing (Squash)

#2165 Fixes #1947 Browser update page action menu
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/Assets.xcassets/icon_hamburger_menu.imageset/Contents.json
  Blockzilla/Assets.xcassets/icon_hamburger_menu.imageset/icon_hamburger_menu.pdf
  Blockzilla/Assets.xcassets/icon_shortcuts.imageset/Contents.json
  Blockzilla/Assets.xcassets/icon_shortcuts.imageset/icon_shortcuts.pdf
  Blockzilla/BrowserToolbar.swift
  Blockzilla/BrowserToolset.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/HomeViewToolbar.swift
  Blockzilla/PhotonActionSheet.swift
  Blockzilla/PhotonActionSheetCell.swift
  Blockzilla/URLBar.swift
  XCUITest/BasicBrowsing.swift
  XCUITest/PastenGoTest.swift
  XCUITest/SettingAppearanceTest.swift
Labels: Needs Landing (Squash)

#2175 Fixes #1955 - Settings - Move Send Usage Data into its own section
  Blockzilla/SettingsViewController.swift
Labels: Needs Landing (Squash)

#2174 Fixes #2137 - Trackers blocked should use international number formatter
  Blockzilla/TrackingProtectionViewController.swift
Labels: Needs Landing (Squash)

#2173 Fixes #2172 - Update the what's new page URL
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/AddSearchEngineViewController.swift
  Blockzilla/AutocompleteSettingViewController.swift
  Blockzilla/SettingsViewController.swift
  Blockzilla/SupportUtils.swift
  Blockzilla/TrackingProtectionViewController.swift
  Blockzilla/UIConstants.swift
  ClientTests/SupportUtilsTest.swift
  Shared/AppInfo.swift
Labels: Needs Landing (Squash)

#2183 No Bug - Small String Updates
  Blockzilla/TrackingProtectionViewController.swift
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#2186 Fixes #1917 The URL bar is empty and the keyboard will pop up after receiving a link via airdrop
  Blockzilla/AppDelegate.swift
Labels: Needs Landing (Squash)

#2182 Fixes #2179 - Do not invalidate strings that only have a case change
  tools/Localizations/Sources/Localizations/ExportTask.swift
Labels: Needs Landing (Squash)

#2185 Fixes #2184 - Add missing strings to UIConstants
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#2190 Fixes #2014 Remove long press on refresh button
  Blockzilla/BrowserToolset.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/InsetButton.swift
Labels: Needs Landing (Squash)

#2176 Fixes #1963 - iPad search suggestions redesign
  Blockzilla/BrowserViewController.swift
  Blockzilla/Colors.xcassets/SearchSuggestionIPad.colorset/Contents.json
  Blockzilla/Colors.xcassets/Suggestion.colorset/Contents.json
  Blockzilla/OverlayView.swift
  Blockzilla/SearchSuggestionsPromptView.swift
  Blockzilla/UIColorExtensions.swift
  Blockzilla/UIConstants.swift
  Blockzilla/UIViewExtensions.swift
Labels: Needs Landing (Squash)

#2187 Fixes #2140 - Disable translucency on bottom toolbar
  Blockzilla/BrowserToolbar.swift
Labels: Needs Landing (Squash)

#2194 Fixes #2189 Add long press on url bar
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#2193 Fixes #2152 - Shield Data does not stretch correctly
  Blockzilla/TrackingProtectionViewController.swift
Labels: Needs Landing (Squash)

#2195 Fixes #2145 - On the search results interface, the top toolbar, address box and search results have different backgrounds
  Blockzilla/BrowserViewController.swift
  Blockzilla/OverlayView.swift
  Blockzilla/URLBar.swift
  Blockzilla/URLBarContainer.swift
Labels: Needs Landing (Squash)

#2198 Fixes #2204 - Update SnapshotHelper.swift
  ScreenshotTests/SnapshotHelper.swift
Labels: Needs Landing (Squash)

#2201 Fixes #2200 - Shortcuts - iPad layout differences
  Blockzilla/BrowserViewController.swift
  Blockzilla/OverlayView.swift
  Blockzilla/SearchSuggestionsPromptView.swift
  Blockzilla/ShortcutView.swift
  Blockzilla/UIColorExtensions.swift
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#2214 Fixes #2205 - SettingAppearanceTest failures after UI changes
  SmokeTestRefresh.xctestplan
  XCUITest/SettingAppearanceTest.swift
Labels: eng:ui-test, eng:automation, Needs Landing (Squash)

#2218 For #2205 - Disable testCheckSettings
  SmokeTestRefresh.xctestplan
Labels: Needs Landing (Squash)

#2220 For #2205 - Disable testCheckSetting()
  SmokeTestRefresh.xctestplan
Labels: Needs Landing (Squash)

#2216 Fixes #2208 - Highlighted search suggestions shows background
  Blockzilla/Colors.xcassets/SearchSuggestionButtonHighlight.colorset/Contents.json
  Blockzilla/InsetButton.swift
  Blockzilla/OverlayView.swift
Labels: Needs Landing (Squash)

#2215 Fixes #2213 - Thin divider line between address bar and search suggestions
  Blockzilla/OverlayView.swift
Labels: Needs Landing (Squash)

#2217 Shortcuts should also show on the app home screen without activated address bar
  Blockzilla/BrowserViewController.swift
  Blockzilla/ShortcutsManager.swift
Labels: Needs Landing (Squash)

#2222 Fixes #2212 Incorrect shortcuts bar layout on smallest horizontal size class
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)
