Repository mozilla-mobile/focus-ios, pull requests merged in 2021-07, with the labels that each got.

#1987 Fixes #1916 - Settings menu is not dismissed after opening a page via notes or external app
  Blockzilla/AppDelegate.swift
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#1989 Fixes #1985 - Page actions sheet is not dismissed after opening a page via notes or external app
  Blockzilla/AppDelegate.swift
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#1988 Fixes #1940 - Splash - Empty State Toolbar
  Blockzilla/UIColorExtensions.swift
  Blockzilla/UIConstants.swift
  Blockzilla/URLBar.swift
  XCUITest/TPSidebarBadge.swift
Labels: Needs Landing (Squash)

#1990 Fixes #1941 - Splash - Bottom Toolbar
  Blockzilla/BrowserToolbar.swift
  Blockzilla/BrowserToolset.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/HomeViewToolbar.swift
  Blockzilla/UIConstants.swift
  Blockzilla/UIImageExtensions.swift
  Blockzilla/URLBar.swift
  XCUITest/PastenGoTest.swift
  XCUITest/TPSidebarBadge.swift
  XCUITest/WebsiteAccessTest.swift
Labels: Needs Landing (Squash)

#1991 Fixes #1942 - Splash - Background Image
  Blockzilla/BrowserViewController.swift
  Blockzilla/HomeView.swift
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#1986 For #1933 - XCUITests fix tests for the full functional test plan suite
  XCUITest/AsianLocaleTest.swift
  XCUITest/BaseTestCase.swift
  XCUITest/CopyTest.swift
  XCUITest/OpenInFocusTest.swift
  XCUITest/PastenGoTest.swift
  XCUITest/SearchProviderTest.swift
  XCUITest/SearchSuggestionsTest.swift
  XCUITest/SettingAppearanceTest.swift
  XCUITest/TPSettingsTest.swift
  XCUITest/WebsiteAccessTest.swift
  XCUITest/WebsiteMemoryTest.swift
Labels: Needs Landing (Squash)

#1996 Fixes #1944 - Splash - Pro Tips
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/AppDelegate.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/HomeView.swift
  Blockzilla/TipManager.swift
  Blockzilla/TipsPageControl.swift
  Blockzilla/UIConstants.swift
  Blockzilla/URIFixup.swift
  ClientTests/URIFixupTests.swift
  XCUITest/AsianLocaleTest.swift
  XCUITest/BaseTestCase.swift
  XCUITest/CopyTest.swift
  XCUITest/OpenInFocusTest.swift
  XCUITest/PastenGoTest.swift
  XCUITest/SearchProviderTest.swift
  XCUITest/SearchSuggestionsTest.swift
  XCUITest/SettingAppearanceTest.swift
  XCUITest/TPSettingsTest.swift
  XCUITest/WebsiteAccessTest.swift
  XCUITest/WebsiteMemoryTest.swift
  bitrise.yml
  screenshots.sh
Labels: Needs Landing (Squash)

#1930 Fixes #1921 - Site duplicate should not be allowed in "URL Autocomplete"
  Blockzilla/Lib/DomainCompletion/DomainCompletion.swift
  ClientTests/DomainCompletionTests.swift
Labels: Needs Landing (Squash)

#2000 Fixes #1999 - Include a post-clone script for Xcode Cloud
  ci_scripts/ci_post_clone.sh
Labels: Needs Landing (Squash)

#2005 Append `/` to domain completions only when no `/` is present.
  Blockzilla/Lib/DomainCompletion/DomainCompletion.swift
Labels: Needs Landing (Squash)

#1995 For #1932 - Run Automated tests on iPad device
  XCUITest/BaseTestCase.swift
  XCUITest/DragAndDropTest.swift
  XCUITest/QuickAddAutocompleteURLTest.swift
  XCUITest/RequestDesktopTest.swift
  XCUITest/SearchProviderTest.swift
  XCUITest/SettingAppearanceTest.swift
  XCUITest/TPSettingsTest.swift
  XCUITest/TPSidebarBadge.swift
  bitrise.yml
Labels: Needs Landing (Squash)

#2011 Fixes #1948 - Browser - Top Toolbar Redesign
  Blockzilla/BrowserViewController.swift
  Blockzilla/UIConstants.swift
  Blockzilla/URLBar.swift
  Blockzilla/URLBarContainer.swift
Labels: Needs Landing (Squash)

#1998 Fixes #1945 - Splash - Erase Message
  Blockzilla/GradientBackgroundView.swift
  Blockzilla/Toast.swift
  Blockzilla/UIConstants.swift
  Blockzilla/en.lproj/Localizable.strings
  XCUITest/PastenGoTest.swift
Labels: Needs Landing (Squash)

#2013 Fixes #1994 - Create a beta track on TestFlight (Bitrise Changes)
  bitrise.yml
Labels: Needs Landing (Squash)

#2002 Fixes #1994 - Create a beta track on TestFlight (Versioning)
  Blockzilla/Info.plist
  ContentBlocker/Info.plist
  FocusIntentExtension/Info.plist
  OpenInFocus/Info.plist
Labels: Needs Landing (Squash)

#1981 l10nScreenshotsTests-add-workflow-Part1-bis
  bitrise.yml
  l10n-screenshots-config.yml
  screenshots.sh
  shipping_locales.txt
Labels: Needs Landing (Squash)

#2018 Fixes - #2010 - "X" icon is not displayed in the URL after steps
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#1978 Get Screenshots on CI: Enable Taskcluster and Taskgraph - Part 2
  .taskcluster.yml
  taskcluster/ci/config.yml
  taskcluster/focusios_taskgraph/__init__.py
  taskcluster/focusios_taskgraph/job.py
  taskcluster/scripts/get-secret.py
  taskcluster/scripts/write-dummy-secret.py
Labels: Needs Landing (Squash)

#2020 Fixes #1949 - Browser - New page loading progress bar colors/style
  Blockzilla/GradientProgressBar.swift
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#2025 Disable cron decision tasks from being generated
  .taskcluster.yml
Labels: Needs Landing

#2022 Fixes 1885 - Upgrade the IPHONEOS_DEPLOYMENT_TARGET to iOS 13.6
  Blockzilla.xcodeproj/project.pbxproj
Labels: Needs Landing (Squash)

#2026 Attempt #2 to silence cron errors
  .cron.yml
  .taskcluster.yml
Labels: Needs Landing

#2028 Fixes #2015 - [iPhone] URL bar layout breaks in landscape
  Blockzilla/BrowserViewController.swift
  Blockzilla/UIConstants.swift
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#2030 Fixes #1950 - Browser - Suggestions & Autocomplete Redesign
  Blockzilla/BrowserViewController.swift
  Blockzilla/Colors.xcassets/Scrim.colorset/Contents.json
  Blockzilla/Colors.xcassets/SearchGradientFirst.colorset/Contents.json
  Blockzilla/Colors.xcassets/SearchGradientFourth.colorset/Contents.json
  Blockzilla/Colors.xcassets/SearchGradientSecond.colorset/Contents.json
  Blockzilla/Colors.xcassets/SearchGradientThird.colorset/Contents.json
  Blockzilla/Colors.xcassets/SearchSeparator.colorset/Contents.json
  Blockzilla/OverlayView.swift
  Blockzilla/UIColorExtensions.swift
  Blockzilla/UIConstants.swift
  Blockzilla/UIViewExtensions.swift
Labels: Needs Landing (Squash)

#1972 Fixes #1895 - Sharing text on Focus is not working
  Blockzilla/AppDelegate.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/URLBar.swift
  OpenInFocus/ActionViewController.swift
Labels: Needs Landing (Squash)

#2035 Fixes #2017 - Focus splash screen is briefly displayed on Klar splash screen
  Blockzilla/Assets.xcassets/img_focus_wordmark.imageset/Contents.json
  Blockzilla/Assets.xcassets/img_focus_wordmark.imageset/img_focus_wordmark.png
  Blockzilla/Assets.xcassets/img_focus_wordmark.imageset/img_focus_wordmark@2x.png
  Blockzilla/Assets.xcassets/img_focus_wordmark.imageset/img_focus_wordmark@3x.png
  Blockzilla/Assets.xcassets/img_klar_wordmark.imageset/Contents.json
  Blockzilla/Assets.xcassets/img_klar_wordmark.imageset/img_klar_wordmark.png
  Blockzilla/Assets.xcassets/img_klar_wordmark.imageset/img_klar_wordmark@2x.png
  Blockzilla/Assets.xcassets/img_klar_wordmark.imageset/img_klar_wordmark@3x.png
  Blockzilla/Assets.xcassets/logo.imageset/Contents.json
  Blockzilla/Assets.xcassets/logo.imageset/logo_focus.pdf
  Blockzilla/Assets.xcassets/logo_klar.imageset/Contents.json
  Blockzilla/Assets.xcassets/logo_klar.imageset/logo_klar.pdf
  Blockzilla/HomeView.swift
  Blockzilla/LaunchScreen.png
  Blockzilla/LaunchScreen.storyboard
  Blockzilla/LaunchScreen@2x.png
  Blockzilla/LaunchScreen@3x.png
  Shared/AppConfig.swift
Labels: Needs Landing (Squash)

#2040 Fixes #2039 - Fix incorrect locale codes in shipping_locales.txt
  shipping_locales.txt
Labels: Needs Uplift

#2029 L10n part4 and part 8 add all scripts needed
  .cron.yml
  .taskcluster.yml
  bitrise.yml
  l10n-screenshots.sh
  taskcluster/ci/docker-image/kind.yml
  taskcluster/ci/generate-screenshots/kind.yml
  taskcluster/focusios_taskgraph/loader/__init__.py
  taskcluster/focusios_taskgraph/loader/screenshots_locales.py
  taskcluster/focusios_taskgraph/routes.py
  taskcluster/focusios_taskgraph/screenshots_locales.py
  taskcluster/focusios_taskgraph/target_tasks.py
  taskcluster/focusios_taskgraph/transforms/__init__.py
  taskcluster/focusios_taskgraph/transforms/bitrise.py
  taskcluster/focusios_taskgraph/transforms/secrets.py
  taskcluster/scripts/bitrise-schedule.py
  taskcluster/scripts/check-screenshots.py
Labels: Needs Landing (Squash)

#2047 L10n follow up missing docker file
  taskcluster/docker/screenshots/Dockerfile
  taskcluster/docker/screenshots/requirements.txt
Labels: Needs Landing (Squash)

#2045 Fixes #1951 - Browser - Autocomplete Arrows
  Blockzilla/BrowserViewController.swift
  Blockzilla/OverlayView.swift
Labels: Needs Landing (Squash)

#2049 l10n follow up 2 missing ci/build directory
  taskcluster/ci/build/kind.yml
  taskcluster/ci/config.yml
Labels: Needs Landing (Squash)

#2050 l10n follow up 3 fix naming error in taskcluster.yml
  .taskcluster.yml
Labels: Needs Landing

#2058 Fixes #2052 - Localize UIApplicationShortcutItemTitle with a key
  Blockzilla/Info.plist
  Blockzilla/en.lproj/InfoPlist.strings
Labels: Needs Landing (Squash)

#2061 Fixes #2054 - Remove the ShareMenu.OpenInFocus string
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#2060 Fixes #2053 - Localize the Settings.bundle
  Blockzilla/Settings.bundle/Root.plist
  Blockzilla/Settings.bundle/en.lproj/Root.strings
Labels: Needs Landing (Squash)

#2064 l10n-follow-up-4-update-L10nBuild-workflow
  bitrise.yml
Labels: Needs Landing

#2070 Fixes #2069 - Undo random punctuation changes
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)
