Repository mozilla-mobile/focus-ios, pull requests merged in 2021-09, with the labels that each got.

#2153 For #2089 - Reenable ui tests refresh
  SmokeTestRefresh.xctestplan
  XCUITest/CollapsedURLTest.swift
  XCUITest/FindInPageTest.swift
  XCUITest/PastenGoTest.swift
  XCUITest/QuickAddAutocompleteURLTest.swift
  XCUITest/SearchProviderTest.swift
  XCUITest/SettingAppearanceTest.swift
  XCUITest/TPSidebarBadge.swift
  XCUITest/WebsiteAccessTest.swift
Labels: Needs Landing (Squash)

#2231 Fixes #2225 [iPad] Home screen logo misbehaves when picking up device
  Blockzilla/HomeView.swift
Labels: Needs Landing (Squash)

#2245 Fixes #2244 - Update Glean to v40
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  bin/sdk_generator.sh
Labels: Needs Landing (Squash)

#2238 Fixes #2059 - Bring the licenses in the Settings.bundle up to date
  Blockzilla/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
  Blockzilla/Settings.bundle/com.mono0926.LicensePlist.plist
  Blockzilla/Settings.bundle/com.mono0926.LicensePlist/AutocompleteTextField.plist
  Blockzilla/Settings.bundle/com.mono0926.LicensePlist/GCDWebServer.plist
  Blockzilla/Settings.bundle/com.mono0926.LicensePlist/onepassword-extension.plist
  Blockzilla/Settings.bundle/com.mono0926.LicensePlist/sentry-cocoa.plist
Labels: Needs Landing (Squash)

#2171 Fixes #2159 - Add a home screen tip about the UI refresh
  Blockzilla/AppDelegate.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/TelemetryIntegration.swift
  Blockzilla/TipManager.swift
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#2249 Fixes #1766 - Enable Glean Debug Tools
  Blockzilla/AppDelegate.swift
Labels: Needs Landing (Squash)

#2246 Fixes #2177 Hamburger menu does not respect safe area in landscape
  Blockzilla/HomeView.swift
Labels: Needs Landing (Squash)

#2254 Fixes #2253 - Include new locales: co an en-GB
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/co.lproj/InfoPlist.strings
  Blockzilla/co.lproj/Intents.strings
  Blockzilla/co.lproj/Intro.strings
  Blockzilla/co.lproj/Localizable.strings
  Blockzilla/en-GB.lproj/InfoPlist.strings
  Blockzilla/en-GB.lproj/Intents.strings
  Blockzilla/en-GB.lproj/Intro.strings
  Blockzilla/en-GB.lproj/Localizable.strings
  ContentBlocker/co.lproj/InfoPlist.strings
  ContentBlocker/en-GB.lproj/InfoPlist.strings
  ScreenshotTests/co.lproj/InfoPlist.strings
  ScreenshotTests/en-GB.lproj/InfoPlist.strings
  XCUITest/co.lproj/InfoPlist.strings
  XCUITest/en-GB.lproj/InfoPlist.strings
Labels: Needs Landing (Squash)

#2250 For #2233 - Update L10n tests to run on refresh
  ScreenshotTests/SnapshotTests.swift
Labels: Needs Landing (Squash)

#2264 Fixes #2263 - AllowsLinkPreview does not work
  Blockzilla/Modules/WebView/WebViewController.swift
Labels: Needs Landing (Squash)

#2286 Fixes #2285 - Update deletion-request ping
  Blockzilla/metrics.yaml
Labels: Needs Landing (Squash)

#2232 Fixes #2092 - Capture telemetry for Shortcuts
  Blockzilla/AppDelegate.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/PageActionSheetItems.swift
  Blockzilla/metrics.yaml
  Documentation/metrics.md
Labels: Needs Landing (Squash)

#2265 Fixes #2093 - Capture telemetry for Tracking Protection
  Blockzilla/AppDelegate.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/TrackingProtectionViewController.swift
  Blockzilla/metrics.yaml
Labels: Needs Landing (Squash)

#2283 Fixes #2094 - Capture Telemetry for Adding Link to Autocomplete
  Blockzilla/AddCustomDomainViewController.swift
  Blockzilla/metrics.yaml
Labels: Needs Landing (Squash)

#2284 Fixes #2227 - Capture telemetry for installed products
  Blockzilla/AppDelegate.swift
  Blockzilla/metrics.yaml
Labels: Needs Landing (Squash)

#2237 Fixes #2236 - Remove Sentry
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Blockzilla/AppDelegate.swift
  Blockzilla/Info.plist
  SentryIntegration.swift
Labels: Needs Code Review

#2280 Fixes #2269 - Get Search Suggestions setting indented
  Blockzilla/SettingsViewController.swift
Labels: Needs Landing (Squash)

#2274 Fixes #2271 - Remove opacity view over home view/ shorcuts in browsing mode
  Blockzilla/BrowserViewController.swift
  Blockzilla/OverlayView.swift
Labels: Needs Landing (Squash)

#2292 Fixes #2257 - Import Strings tool logs to incorrect file
  tools/import-strings.sh
Labels: Needs Landing (Squash)

#2294 Fixes #2243 - Text truncation issues on Tracking Protection settings
  Blockzilla/TrackingProtectionViewController.swift
Labels: Needs Landing (Squash)

#2306 Fixes #2229 - Incorrect shortcuts bar layout when using splitscreen in portrait view
  Blockzilla/BrowserViewController.swift
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#2279 Fixes #2239 Refactor the tip manager
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/AppDelegate.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/HomeView.swift
  Blockzilla/Modules/WebView/WebViewController.swift
  Blockzilla/PageActionSheetItems.swift
  Blockzilla/SettingsViewController.swift
  Blockzilla/SiriFavoriteViewController.swift
  Blockzilla/TipManager.swift
  Blockzilla/UserDefault.swift
Labels: Needs Landing (Squash)

#2307 Fixes #2273 - Background colors misbehaves tilting the device
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/BrowserViewController.swift
  Blockzilla/HomeView.swift
  Blockzilla/UIApplication+Orientation.swift
Labels: Needs Landing (Squash), iPad, Regression

#2291 For #2282 - L10n new tests to cover more screens
  ScreenshotTests/SnapshotTests.swift
Labels: Needs Landing (Squash)

#2311 Fixes #2223 - Incorrect icon will be displayed for the search suggestion after manually typing the full URL
  Blockzilla/OverlayView.swift
Labels: Needs Landing (Squash)

#2309 Issue2308 - l10n ci implementation into refresh
  .cron.yml
  .taskcluster.yml
  bitrise.yml
  l10n-screenshots-config.yml
  l10n-screenshots.sh
  screenshots.sh
  shipping_locales.txt
  taskcluster/ci/build/kind.yml
  taskcluster/ci/config.yml
  taskcluster/ci/docker-image/kind.yml
  taskcluster/ci/generate-screenshots/kind.yml
  taskcluster/docker/screenshots/Dockerfile
  taskcluster/docker/screenshots/requirements.txt
  taskcluster/focusios_taskgraph/__init__.py
  taskcluster/focusios_taskgraph/job.py
  taskcluster/focusios_taskgraph/loader/__init__.py
  taskcluster/focusios_taskgraph/loader/screenshots_locales.py
  taskcluster/focusios_taskgraph/routes.py
  taskcluster/focusios_taskgraph/screenshots_locales.py
  taskcluster/focusios_taskgraph/target_tasks.py
  taskcluster/focusios_taskgraph/transforms/__init__.py
  taskcluster/focusios_taskgraph/transforms/bitrise.py
  taskcluster/focusios_taskgraph/transforms/secrets.py
  taskcluster/scripts/bitrise-schedule.py
  taskcluster/scripts/check-screenshots.py
  taskcluster/scripts/get-secret.py
  taskcluster/scripts/write-dummy-secret.py
Labels: Needs Landing (Squash)

#2315 String Import 2021-09-09
  Blockzilla/Settings.bundle/es-ES.lproj/Root.strings
  Blockzilla/es-ES.lproj/InfoPlist.strings
  Blockzilla/es-ES.lproj/Intents.strings
  Blockzilla/es-ES.lproj/Localizable.strings
  Blockzilla/lt.lproj/Localizable.strings
  Blockzilla/lv.lproj/Localizable.strings
  Blockzilla/pt-BR.lproj/Intro.strings
  Blockzilla/pt-BR.lproj/Localizable.strings
Labels: Needs Landing (Squash)

#2317 Fixes #2316 - Only show the sharing of blocked trackers for English locales
  Blockzilla/HomeView.swift
  Blockzilla/TipManager.swift
Labels: Needs Landing (Squash)

#2318 Fixes #2310 - Setup an email for Focus iOS Data Stewards
  Blockzilla/metrics.yaml
Labels: Needs Landing (Squash)

#2325 Fixes #2300 - On the New Tab Page, if the clear 'x' symbol is selected, shortcut tile appears with a solid colour background
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#2326 Fixes #2221 Refresh button not displayed after hiding and revealing the URL bar
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#2323 Fixes #2230 - Hamburger menu is in the wrong place
  Blockzilla/BrowserViewController.swift
  Blockzilla/HomeViewToolbar.swift
  Blockzilla/UIConstants.swift
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#2289 For #2281 - Fix Full Functional test Refresh
  Blockzilla.xcodeproj/project.pbxproj
  FullFunctionalTests.xctestplan
  XCUITest/AsianLocaleTest.swift
  XCUITest/BaseTestCase.swift
  XCUITest/BasicBrowsing.swift
  XCUITest/CollapsedURLTest.swift
  XCUITest/DragAndDropTest.swift
  XCUITest/FindInPageTest.swift
  XCUITest/QuickAddAutocompleteURLTest.swift
  XCUITest/RequestDesktopTest.swift
  XCUITest/SearchProviderTest.swift
  XCUITest/SearchSuggestionsTest.swift
  XCUITest/SettingAppearanceTest.swift
  XCUITest/TPSettingsTest.swift
  XCUITest/TPSidebarBadge.swift
  XCUITest/WebsiteAccessTest.swift
  bitrise.yml
Labels: Needs Landing (Squash)

#2336 Fixes #2329 - Address bar is too narrow
  Blockzilla/BrowserViewController.swift
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#2334 Fixes #2211 It is not possible to tap the pro tips or menu button if the location bar is active
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/BrowserViewController.swift
  Blockzilla/HomeView.swift
  Blockzilla/HomeViewController.swift
  Blockzilla/TipManager.swift
  Blockzilla/TipsPageControl.swift
  ShareTrackersViewController.swift
  TipViewController.swift
  TipsPageViewController.swift
  UIViewController+Child.swift
Labels: Needs Landing (Squash)

#2331 Fixes #2268 - String truncation in Settings screen
  Blockzilla/SettingsViewController.swift
Labels: Needs Landing (Squash)

#2348 Fixes #2347 Find in page option not shown when typing on the url bar once a site is loaded
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#2345 Fixes #2340 - Include the build number in the About screen
  Blockzilla/AboutViewController.swift
Labels: Needs Landing (Squash)

#2335 String Import 2021-09-13
  Blockzilla/ne-NP.lproj/InfoPlist.strings
  Blockzilla/ne-NP.lproj/Intents.strings
  Blockzilla/ne-NP.lproj/Localizable.strings
  Blockzilla/zh-CN.lproj/InfoPlist.strings
  Blockzilla/zh-CN.lproj/Localizable.strings
Labels: Needs Landing (Squash)

#2349 Fixes #2224 - Shortcuts overlap the Focus logo on some device
  Blockzilla/BrowserViewController.swift
  Blockzilla/HomeViewController.swift
  Blockzilla/UIConstants.swift
  TipViewController.swift
  TipsPageViewController.swift
  XCUITest/WebsiteAccessTest.swift
Labels: Needs Landing (Squash)

#2351 Fixes #2303 - Match font sizes and colours of top and bottom descriptions in Settings and Tracking Protection panel
  Blockzilla/AboutViewController.swift
  Blockzilla/AddSearchEngineViewController.swift
  Blockzilla/AutocompleteSettingViewController.swift
  Blockzilla/Colors.xcassets/AccentButton.colorset/Contents.json
  Blockzilla/Colors.xcassets/SecondaryDark.colorset/Contents.json
  Blockzilla/SettingsViewController.swift
  Blockzilla/SiriFavoriteViewController.swift
  Blockzilla/TrackingProtectionViewController.swift
  Blockzilla/UIColorExtensions.swift
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#2350 XCUITest - fix search provider test
  XCUITest/SearchProviderTest.swift
Labels: Needs Landing

#2354 Fixes #2302 - Inset grouped table row in Settings and Tracking Protection have top and bottom horizontal rulers
  Blockzilla/SettingsViewController.swift
  Blockzilla/TrackingProtectionViewController.swift
  Blockzilla/UIConstants.swift
  Blockzilla/UITableViewCellExtensions.swift
Labels: Needs Landing (Squash)

#2346 Fixes #2301 Match appearance and behaviour of New Tab Page carousel to system native Page Controls
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/Extensions/UIViewController+Child.swift
  Blockzilla/HomeViewController.swift
  Blockzilla/Pro Tips/ShareTrackersViewController.swift
  Blockzilla/Pro Tips/TipViewController.swift
  Blockzilla/Pro Tips/TipsPageViewController.swift
  Blockzilla/SettingsViewController.swift
  Blockzilla/TipManager.swift
Labels: Needs Landing (Squash)

#2355 Fixes #2278 - The "X" button is displayed in the URL bar but not text is typed.
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#2358 Fix #2337 Dismiss url bar focused button (<) is missing the very first time the app is launched in non English locales
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#2356 Fixes #2272 - Menu items layout is broken in landscape
  Blockzilla/SettingsViewController.swift
Labels: Needs Landing (Squash)

#2364 Fixes #2362 - Toolset is hidden
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#2381 Fixes #2376 - Pro tip touch target area is too small
  Blockzilla/Pro Tips/TipViewController.swift
Labels: Needs Landing (Squash)

#2383 Fixes #2375 - Tips pagination hidden below keyboard
  Blockzilla/HomeViewController.swift
  Blockzilla/Pro Tips/TipsPageViewController.swift
Labels: Needs Landing (Squash)

#2380 Fixes #2357 - Do not activate the URL bar when the app is foregrounded with a website loaded
  Blockzilla/BrowserViewController.swift
  XCUITest/PastenGoTest.swift
  XCUITest/SettingAppearanceTest.swift
  XCUITest/WebsiteAccessTest.swift
Labels: Needs Landing (Squash)

#2386 Fixes #2384 - On iPad with smaller app width the toolbar or hamburger menu is missing
  Blockzilla/BrowserViewController.swift
  Blockzilla/HomeViewToolbar.swift
Labels: Needs Landing (Squash)

#2387 Fixes #2226 - The URL bar is not properly dismissed when dismissing the keyboard via keyboard button
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#2385 Fixes #2366 - Updated app icons
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon-40.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon-40@2x.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon-40@3x.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon-60@2x.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon-60@3x.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon-72.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon-72@2x.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon-76.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon-76@2x.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon-83.5@2x.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon-small-50.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon-small-50@2x.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon-small.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon-small@2x.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon-small@3x.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/icon@2x.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/ios-marketing.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/notification-icon@2x.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/notification-icon@3x.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/notification-icon~ipad.png
  Blockzilla/Assets.xcassets/AppIcon.appiconset/notification-icon~ipad@2x.png
Labels: Needs Landing (Squash)

#2392 Fixes #2365 - Toolset back/forward buttons hidden in landscape mode
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#2402 Fixes #2401 - Keyboard does not open and home screen tips are cut off
  Blockzilla/BrowserViewController.swift
  XCUITest/PastenGoTest.swift
  XCUITest/SettingAppearanceTest.swift
  XCUITest/WebsiteAccessTest.swift
Labels: Needs Landing (Squash)

#2403 Fixes #2369 - Suggestions overlap append button
  Blockzilla/OverlayView.swift
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#2406 Fixes #2266 - Do not generate Documentation/metrics.md anymore
  Blockzilla.xcodeproj/project.pbxproj
  Documentation/metrics.md
Labels: Needs Landing (Squash)

#2408 Fixes #2377 - Request mobile site icon is squashed
  Blockzilla/PhotonActionSheet.swift
  Blockzilla/PhotonActionSheetCell.swift
  Blockzilla/SearchSettingsViewController.swift
  Blockzilla/UIImageExtensions.swift
Labels: Needs Landing (Squash)

#2409 Fixes #2322 - Add a space after appending a search suggestion
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#2410 For #2405 - Update smoketest to run on main
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/xcshareddata/xcschemes/Focus.xcscheme
  Blockzilla.xcodeproj/xcshareddata/xcschemes/Klar.xcscheme
  SmokeTest.xctestplan
  SmokeTestRefresh.xctestplan
  bitrise.yml
Labels: Needs Landing (Squash)

#2411 Fixes #2352 - The Restore Default Search Engines button does not work
  Blockzilla/SearchEngineManager.swift
  Blockzilla/SearchSettingsViewController.swift
Labels: Needs Landing (Squash)

#2412 Fixes #2374 - Updated colors for the location bar and notification
  Blockzilla/Colors.xcassets/LocationBar.colorset/Contents.json
  Blockzilla/Toast.swift
  Blockzilla/UIColorExtensions.swift
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#2416 Fixes #2415 - Sharing text on Focus is not working
  Blockzilla/AppDelegate.swift
  Blockzilla/BrowserViewController.swift
  OpenInFocus/ActionViewController.swift
Labels: Needs Landing (Squash)

#2417 Fixes #2413 - Continuous haptic feedback when long pressing on shortcut
  Blockzilla/ShortcutView.swift
Labels: Needs Landing (Squash)

#2419 Missing updates for XCUITest Full Test Plan
  XCUITest/AsianLocaleTest.swift
  XCUITest/FindInPageTest.swift
  XCUITest/UserAgentTest.swift
Labels: Needs Landing

#2418 Fixes #2377: square frame and margin on request_mobile_site_activity.pdf
  Blockzilla/Assets.xcassets/request_mobile_site_activity.imageset/request_mobile_site_activity.pdf
Labels: Needs Landing (Squash)

#2421 Revert "Fixes #2377 - Request mobile site icon is squashed"
  Blockzilla/PhotonActionSheet.swift
  Blockzilla/PhotonActionSheetCell.swift
  Blockzilla/SearchSettingsViewController.swift
  Blockzilla/UIImageExtensions.swift
Labels: Needs Landing (Squash)

#2423 Fixes #2373 - Address bar unresponsive after dismissing keyboard
  Blockzilla/BrowserViewController.swift
  Blockzilla/HomeViewController.swift
Labels: Needs Landing (Squash)

#2425 For #2424 - Bitrise: update to gen2 machines
  bitrise.yml
Labels: Needs Landing (Squash)

#2429 Fixes #2295 - Bottom toolbar does not use new background colour
  Blockzilla/BrowserToolbar.swift
Labels: Needs Landing (Squash)

#2437 Fixes #2414 - Labels in settings which require two lines are cut off
  Blockzilla/SettingsViewController.swift
Labels: Needs Landing (Squash)

#2441 Fixes #2428 - Add "Help" menu item to New Tab Page Main Application / Hamburger Menu
  Blockzilla/Assets.xcassets/icon_help.imageset/Contents.json
  Blockzilla/Assets.xcassets/icon_help.imageset/icon_help.pdf
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#2443 Fixes #2442 - What's new back button different color
  Blockzilla/SettingsContentViewController.swift
Labels: Needs Landing (Squash)

#2444 Fixes #2440 - Transparent navigation bar on iOS 15
  Blockzilla/AppDelegate.swift
Labels: Needs Landing (Squash)

#2448 Fixes #2333 - Tracking protection menu in lanscape - some strings does not respect the safe area
  Blockzilla/AddSearchEngineViewController.swift
  Blockzilla/TrackingProtectionViewController.swift
Labels: Needs Landing (Squash)

#2455 Fixes #2445 - Your rights section not matching color scheme
  Blockzilla/LocalWebServer/style.css
Labels: Needs Landing (Squash)

#2457 Fix #2434 Upgrade to the latest Swift version
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/IntroViewController.swift
  Blockzilla/OverlayView.swift
  Blockzilla/SettingsViewController.swift
  Blockzilla/ShortcutsManager.swift
  OpenInFocus/ActionViewController.swift
  Shared/AppInfo.swift
Labels: Needs Landing (Squash)

#2456 Fixes #2446 - Add new search engine screen is not shown completely in lanscape
  Blockzilla/AddSearchEngineViewController.swift
Labels: Needs Landing (Squash)

#2466 Fixes #2453 - "Restore Default Search Engines" doesn't work for removed default search engines
  Blockzilla/SearchEngineManager.swift
Labels: Needs Landing (Squash)

#2458 Fixes #2435 Address all compile warnings from Xcode 13 transition
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/AboutViewController.swift
  Blockzilla/AddCustomDomainViewController.swift
  Blockzilla/AddSearchEngineViewController.swift
  Blockzilla/AutocompleteTextField.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/DataExtensions.swift
  Blockzilla/FindInPageBar.swift
  Blockzilla/HomeViewController.swift
  Blockzilla/IntroViewController.swift
  Blockzilla/KeyboardHelper.swift
  Blockzilla/Modules/WebView/WebViewController.swift
  Blockzilla/OverlayView.swift
  Blockzilla/PhotonActionSheet.swift
  Blockzilla/SearchSettingsViewController.swift
  Blockzilla/SearchSuggestionsPromptView.swift
  Blockzilla/SettingsContentViewController.swift
  Blockzilla/SettingsViewController.swift
  Blockzilla/ShortcutsManager.swift
  Blockzilla/TrackingProtectionViewController.swift
  Blockzilla/UIViewExtensions.swift
  Blockzilla/URLBar.swift
  Bytes.swift
  Deferred/ReadWriteLock.swift
  OpenInFocus/ActionViewController.swift
Labels: Needs Landing (Squash)

#2477 Fixes #2327 - Different font sizes in same tab menu - non English locales
  Blockzilla/PhotonActionSheetCell.swift
Labels: Needs Landing (Squash)

#2472 Fixes #2471 - Shortcuts menu is incorrectly positioned after switching orientation
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#2473 Fixes #2450 - URL bar is unresponsive after backgrounding/foregrounding the app while the URL context menu is open
  Blockzilla/AppDelegate.swift
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#2475 Fixes #2474 Missing progress bar
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#2486 Fixes #2485 - Pre-land the strings for Theme Settings
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#2480 Fixes #2321 - Settings' "Backwards" button is strange, should be "Done" or cross icon at top-right
  Blockzilla/SettingsViewController.swift
Labels: Needs Landing (Squash)

#2431 Fixes #2439 - Update CI to use Xcode 13
  Blockzilla.xcodeproj/xcshareddata/xcschemes/Focus.xcscheme
  ClientTests/SearchEngineManagerTests.swift
  FullFunctionalTests.xctestplan
  SmokeTest.xctestplan
  XCUITest/BaseTestCase.swift
  XCUITest/BasicBrowsing.swift
  bitrise.yml
Labels: Needs Landing (Squash)

#2497 update-release-workflow-xcode13
  bitrise.yml
Labels: Needs Landing (Squash)

#2501 Fixes #2499 - Downgrade the IPHONEOS_DEPLOYMENT_TARGET to iOS 13.0
  Blockzilla.xcodeproj/project.pbxproj
Labels: Needs Uplift

#2500 Fixes #2498 - Remove old workflows and branch references from bitrise.yml
  bitrise.yml
Labels: Needs Landing (Squash)
