Repository mozilla-mobile/focus-ios, pull requests merged in 2021-05, with the labels that each got.

#1799 Fixes #1773 - Move Sentry from Carthage to Swift Package Manager
  Blockzilla.xcodeproj/project.pbxproj
  Cartfile
  Cartfile.resolved
  SentryIntegration.swift
Labels: Needs Landing (Squash)

#1801 Fixes #1778 - Move Fuzi from Carthage to Swift Package Manager
  Blockzilla.xcodeproj/project.pbxproj
  Cartfile
  Cartfile.resolved
Labels: Needs Landing (Squash)

#1809 Speed up UI tests by disabling the First Run UI by default
  Blockzilla/AppDelegate.swift
  Shared/AppInfo.swift
  XCUITest/AsianLocaleTest.swift
  XCUITest/BaseTestCase.swift
  XCUITest/CollapsedURLTest.swift
  XCUITest/CopyTest.swift
  XCUITest/DragAndDropTest.swift
  XCUITest/FindInPageTest.swift
  XCUITest/OnboardingTest.swift
  XCUITest/OpenInFocusTest.swift
  XCUITest/PastenGoTest.swift
  XCUITest/QuickAddAutocompleteURLTest.swift
  XCUITest/RequestDesktopTest.swift
  XCUITest/SearchProviderTest.swift
  XCUITest/SearchSuggestionsTest.swift
  XCUITest/SettingAppearanceTest.swift
  XCUITest/TPSettingsTest.swift
  XCUITest/TPSidebarBadge.swift
  XCUITest/UserAgentTest.swift
  XCUITest/WebsiteAccessTest.swift
  XCUITest/WebsiteMemoryTest.swift
Labels: Needs Landing (Squash)

#1785 Fixes #1782 - Enable "Automatically Manage Signing" for FocusDebug/KlarDebug
  Blockzilla.xcodeproj/project.pbxproj
Labels: Needs Landing (Squash)

#1787 Fixes #1781 - Only include the com.apple.developer.web-browser entitlement on CI
  Focus.entitlements
  FocusEnterprise.entitlements
  Klar.entitlements
  KlarEnterprise.entitlements
Labels: Needs Landing (Squash)

#1807 Fixes #1771 - Remove the GCDWebServer dependency
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/AboutViewController.swift
  Blockzilla/AppDelegate.swift
  Blockzilla/BlockerEnabledDetector.swift
  Blockzilla/LocalWebServer/LocalWebServer.swift
  Blockzilla/SafariInstructionsViewController.swift
  Blockzilla/SettingsViewController.swift
  Cartfile
  Cartfile.resolved
  XCUITest/CollapsedURLTest.swift
  XCUITest/CopyTest.swift
  XCUITest/FindInPageTest.swift
  XCUITest/TPSidebarBadge.swift
  XCUITest/WebsiteAccessTest.swift
Labels: Needs Landing (Squash)

#1818 Fixes #1782 - Enable "Automatically Manage Signing" for FocusDebug/KlarDebug
  Blockzilla.xcodeproj/project.pbxproj
Labels: Needs Landing (Squash)

#1815 Fixes #1800 - Enable Parallel UI Tests
  Blockzilla.xcodeproj/xcshareddata/xcschemes/Focus.xcscheme
  Blockzilla.xcodeproj/xcshareddata/xcschemes/Klar.xcscheme
  ClientTests/SearchEngineManagerTests.swift
  ClientTests/SearchEngineTests.swift
  XCUITest/BaseTestCase.swift
  XCUITest/TPSidebarBadge.swift
  XCUITest/WebsiteMemoryTest.swift
Labels: Needs Landing (Squash)

#1817 Fixes #1802 - Move the AutocompleteTextField dependency into Focus
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/AddCustomDomainViewController.swift
  Blockzilla/AutocompleteTextField.swift
  Blockzilla/Lib/DomainCompletion/DomainCompletion.swift
  Blockzilla/URLBar.swift
  Cartfile
  Cartfile.resolved
Labels: Needs Landing (Squash)

#1822 For #1786 - Store Bitrise config into version control
  bitrise.yml
Labels: Needs Landing

#1826 Fixes #1825 - Move Telemetry-iOS from Carthage to Swift Package Manager
  Blockzilla.xcodeproj/project.pbxproj
  Cartfile
  Cartfile.resolved
Labels: Needs Landing (Squash)

#1819 Fixes #1772 - Remove the AgileBits/onepassword-extension dependency
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/Modules/WebView/WebViewController.swift
  Blockzilla/OpenUtils.swift
  Cartfile
  Cartfile.resolved
Labels: Needs Landing (Squash)

#1828 Fixes #1827 - Move Glean from Carthage to Swift Package Manager
  Blockzilla.xcodeproj/project.pbxproj
  Cartfile
  Cartfile.resolved
  bitrise.yml
Labels: Needs Landing (Squash)

#1836 Fixes #1835 - Drop Carthage
  Blockzilla.xcodeproj/project.pbxproj
  Cartfile
  Cartfile.resolved
  README.md
  bitrise.yml
  carthage_command.sh
  checkout.sh
  content-blocker-lib-ios/ContentBlockerGen/Sources/ContentBlockerGen/main.swift
Labels: Needs Landing (Squash)

#1843 Fixes #1842 - AutoCompleteTextField uses some deprecated String methods
  Blockzilla/AutocompleteTextField.swift
Labels: Needs Landing (Squash)

#1845 Fixes #1824 - Add a CODEOWNERS to require reviews for bitrise.yml changes
  .github/CODEOWNERS
Labels: Needs Landing (Squash)

#1853 Fixes #1781 - Only include the com.apple.developer.web-browser entitlement on CI
  bitrise.yml
Labels: Needs Landing (Squash)

#1854 For #1823 - Add Slack Notification to Bitrise Workflow
  bitrise.yml
Labels: Needs Landing (Squash)

#1868 Fix #1864 - Add Launch external application test
  Blockzilla.xcodeproj/project.pbxproj
  XCUITest/BasicBrowsing.swift
Labels: Needs Landing (Squash)

#1701 Fixes #1692 - Long pressing on links does not open the context menu
  Blockzilla/Modules/WebView/WebViewController.swift
Labels: Do Not Land, Needs Review

#1869 For #1862 - Add Navigation Toolbar Smoke test
  XCUITest/BasicBrowsing.swift
  XCUITest/WebsiteAccessTest.swift
Labels: Needs Landing (Squash)

#1840 Fixes #1816 - Clean up imported frameworks
  Blockzilla.xcodeproj/project.pbxproj
Labels: Needs Landing (Squash)

#1874 Fixes #1833 - Make sure we pull in Glean from the official repository
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Landing (Squash)
