Repository mozilla-mobile/focus-ios, pull requests merged in 2021-06, with the labels that each got.

#1883 For #1882 - UI tests create smoketest plan
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/xcshareddata/xcschemes/Focus.xcscheme
  Blockzilla.xcodeproj/xcshareddata/xcschemes/Klar.xcscheme
  SmokeTest.xctestplan
  XCUITest/OnboardingTest.swift
  XCUITest/PastenGoTest.swift
  XCUITest/SettingAppearanceTest.swift
  XCUITest/TPSidebarBadge.swift
  XCUITest/WebsiteAccessTest.swift
  bitrise.yml
Labels: Needs Landing (Squash)

#1870 Fixes #1858 - Long pressing the URL and tapping Paste only selects the URL
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#1865 For #1863 - Update L10n tests
  Blockzilla.xcodeproj/project.pbxproj
  ScreenshotTests/MarketingTests.swift
  ScreenshotTests/SnapshotHelper.swift
  ScreenshotTests/SnapshotTests.swift
  screenshots.sh
Labels: Needs Landing (Squash)

#1888 For #1859 - UI tests add Integration test
  XCUITest/SettingAppearanceTest.swift
Labels: Needs Landing

#1898 Fixes #1765 - Opening a link in Focus as default browser will focus the URL bar
  Blockzilla/AppDelegate.swift
Labels: Needs Landing (Squash)

#1891 Fixes #1867 - Youtube videos do not play in full screen on iPad
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/FullScreen.js
  Blockzilla/Modules/WebView/WebViewController.swift
Labels: Needs Landing (Squash)

#1907 Fixes #1896 - Upgrade to Glean 39.0.2
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Landing (Squash)

#1904 Fixes #1901 - Do not use automatically manage signing for release builds
  Blockzilla.xcodeproj/project.pbxproj
Labels: Needs Landing (Squash)

#1877 Fixes #1876 - Clean up bitrise.yml
  bitrise.yml
Labels: Needs Landing (Squash)

#1911 Fixes #1846 - Open in Focus does not work in some apps
  OpenInFocus/Info.plist
Labels: Needs Landing (Squash), Uplift

#1918 For #1894 - Disable XCUI AdBlocking test
  XCUITest/BasicBrowsing.swift
Labels: Needs Landing, Needs Review

#1893 For #1892 - XCUITests create Full Functional Test Plan for scheduled builds
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/xcshareddata/xcschemes/Focus.xcscheme
  Blockzilla.xcodeproj/xcshareddata/xcschemes/Klar.xcscheme
  FullFunctionalTests.xctestplan
  bitrise.yml
Labels: Needs Landing (Squash)

#1925 Fixes #1924 - Use Bitrise Second Gen build machines
  bitrise.yml
Labels: Needs Landing (Squash)

#1931 For #1929 - XCUITest refactor BaseTest case
  XCUITest/BaseTestCase.swift
  XCUITest/BasicBrowsing.swift
  XCUITest/CollapsedURLTest.swift
  XCUITest/CopyTest.swift
  XCUITest/FindInPageTest.swift
  XCUITest/OnboardingTest.swift
  XCUITest/OpenInFocusTest.swift
  XCUITest/PastenGoTest.swift
  XCUITest/QuickAddAutocompleteURLTest.swift
  XCUITest/RequestDesktopTest.swift
  XCUITest/SearchProviderTest.swift
  XCUITest/SearchSuggestionsTest.swift
  XCUITest/SettingAppearanceTest.swift
  XCUITest/TPSettingsTest.swift
  XCUITest/TPSidebarBadge.swift
  XCUITest/UserAgentTest.swift
  XCUITest/WebsiteAccessTest.swift
  XCUITest/WebsiteMemoryTest.swift
Labels: Needs Landing (Squash)

#1966 For #1863 - Get Ll10n screenshots on CI - Part1
  bitrise.yml
  screenshots.sh
Labels: Needs Landing (Squash)

#1974 Fixes #1936 - Import Images
  Blockzilla/Assets.xcassets/Contents.json
  Blockzilla/Assets.xcassets/background_landscape.imageset/Contents.json
  Blockzilla/Assets.xcassets/background_landscape.imageset/background_ipad_landscape.pdf
  Blockzilla/Assets.xcassets/background_landscape.imageset/background_iphone_landscape.pdf
  Blockzilla/Assets.xcassets/background_portrait.imageset/Contents.json
  Blockzilla/Assets.xcassets/background_portrait.imageset/background_ipad_portrait.pdf
  Blockzilla/Assets.xcassets/background_portrait.imageset/background_iphone_portrait.pdf
  Blockzilla/Assets.xcassets/logo.imageset/Contents.json
  Blockzilla/Assets.xcassets/logo.imageset/logo.pdf
Labels: Needs Landing (Squash)

#1973 Fixes #1935 - Define colors
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/Colors.xcassets/Above.colorset/Contents.json
  Blockzilla/Colors.xcassets/Accent.colorset/Contents.json
  Blockzilla/Colors.xcassets/AccentButton.colorset/Contents.json
  Blockzilla/Colors.xcassets/CfrFirst.colorset/Contents.json
  Blockzilla/Colors.xcassets/CfrSecond.colorset/Contents.json
  Blockzilla/Colors.xcassets/Contents.json
  Blockzilla/Colors.xcassets/Divider.colorset/Contents.json
  Blockzilla/Colors.xcassets/Foundation.colorset/Contents.json
  Blockzilla/Colors.xcassets/GradientFirst.colorset/Contents.json
  Blockzilla/Colors.xcassets/GradientSecond.colorset/Contents.json
  Blockzilla/Colors.xcassets/GradientThird.colorset/Contents.json
  Blockzilla/Colors.xcassets/PrimaryText.colorset/Contents.json
  Blockzilla/Colors.xcassets/SecondaryText.colorset/Contents.json
  Blockzilla/Colors.xcassets/SecondayButton.colorset/Contents.json
  Blockzilla/Colors.xcassets/Warning.colorset/Contents.json
  Blockzilla/UIColorExtensions.swift
Labels: Needs Landing

#1976 Fixes #1927 - Refactor URLFixup.getURL
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/URIFixup.swift
  ClientTests/URIFixupTests.swift
Labels: Needs Landing

#1977 Fixes #1939 - Launch Screen
  Blockzilla/Assets.xcassets/background.imageset/Contents.json
  Blockzilla/Assets.xcassets/background.imageset/background_ipad_landscape.pdf
  Blockzilla/Assets.xcassets/background.imageset/background_ipad_portrait.pdf
  Blockzilla/Assets.xcassets/background.imageset/background_iphone_landscape-1.pdf
  Blockzilla/Assets.xcassets/background.imageset/background_iphone_landscape.pdf
  Blockzilla/Assets.xcassets/background.imageset/background_iphone_portrait.pdf
  Blockzilla/LaunchScreen.storyboard
Labels: Needs Landing
