Repository mozilla-mobile/focus-ios, pull requests merged in 2021-10, with the labels that each got.

#2509 Fixes #2508 - Update the shavar lists to 93.0
  checkout.sh
Labels: Needs Uplift

#2228 Fixes #1866 - Integrate Nimbus into Focus
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Blockzilla/AppDelegate.swift
Labels: Needs Landing (Squash)

#2517 Fixes #2051 - Remove unused LSApplicationQueriesSchemes from Info.plist
  Blockzilla/Info.plist
Labels: Needs Landing (Squash)

#2525 Update README to reflect new Xcode requirements
  README.md
Labels: Needs Landing (Squash)

#2514 Fixes #2513 - Create a tool to more easily change the app version
  tools/set-version.sh
Labels: Needs Landing (Squash)

#2510 Fixes #2479 - Implement new shield/lock designs
  Blockzilla/Assets.xcassets/connection_not_secure.imageset/Contents.json
  Blockzilla/Assets.xcassets/connection_not_secure.imageset/connection_not_secure.pdf
  Blockzilla/BrowserViewController.swift
  Blockzilla/Modules/WebView/WebViewController.swift
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#2518 Fixes #1852 - Add keyboard shortcut for Find in Page
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash), hacktoberfest-accepted

#2526 Fixes #2507 - toggling tracking protection (only) from settings not working
  Blockzilla/SettingsViewController.swift
Labels: Needs Landing (Squash)

#2540 Fixes #2535 - On Home screen, wrong icon is displayed after tracking protection is toggled off
  Blockzilla/BrowserViewController.swift
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#2541 Fixes #2529 - Shortcuts background present on home view after deleting a shortcut
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#2536 String Import 2021-10-05
  Blockzilla/Settings.bundle/ca.lproj/Root.strings
  Blockzilla/ca.lproj/InfoPlist.strings
  Blockzilla/ca.lproj/Intents.strings
  Blockzilla/ca.lproj/Localizable.strings
  Blockzilla/co.lproj/Intro.strings
  Blockzilla/co.lproj/Localizable.strings
  Blockzilla/cs.lproj/Localizable.strings
  Blockzilla/cy.lproj/Localizable.strings
  Blockzilla/de.lproj/Localizable.strings
  Blockzilla/dsb.lproj/Localizable.strings
  Blockzilla/el.lproj/Localizable.strings
  Blockzilla/es-AR.lproj/Localizable.strings
  Blockzilla/es-CL.lproj/Localizable.strings
  Blockzilla/es-ES.lproj/Localizable.strings
  Blockzilla/he.lproj/Localizable.strings
  Blockzilla/hsb.lproj/Localizable.strings
  Blockzilla/hu.lproj/Localizable.strings
  Blockzilla/ia.lproj/Localizable.strings
  Blockzilla/id.lproj/Localizable.strings
  Blockzilla/it.lproj/Localizable.strings
  Blockzilla/ja.lproj/Localizable.strings
  Blockzilla/kab.lproj/Localizable.strings
  Blockzilla/lt.lproj/Localizable.strings
  Blockzilla/nl.lproj/Localizable.strings
  Blockzilla/pt-BR.lproj/Localizable.strings
  Blockzilla/pt-PT.lproj/Localizable.strings
  Blockzilla/ru.lproj/Localizable.strings
  Blockzilla/sk.lproj/Localizable.strings
  Blockzilla/sl.lproj/Localizable.strings
  Blockzilla/sv.lproj/Localizable.strings
  Blockzilla/tr.lproj/Localizable.strings
  Blockzilla/uk.lproj/Localizable.strings
  Blockzilla/vi.lproj/Localizable.strings
  Blockzilla/zh-CN.lproj/Localizable.strings
  Blockzilla/zh-TW.lproj/Localizable.strings
Labels: Needs Landing (Squash)

#2546 Fixes #2481 - Enable WKWebViewConfigure.upgradeKnownHostsToHTTPS
  Blockzilla/Modules/WebView/WebViewController.swift
Labels: Needs Landing (Squash)
