Repository mozilla-mobile/focus-ios, pull requests merged in 2022-10, with the labels that each got.

#3495 Fixes #3475 Default search engine telemetry addition
  Blockzilla/AppDelegate.swift
  Blockzilla/metrics.yaml
Labels: Needs Landing (Squash), Needs Data Review

#3487 Fixes-3439-Telemetry requirements for onboarding optimisations
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/BrowserViewController.swift
  Blockzilla/Onboarding/OnboardingFactory.swift
  Blockzilla/Utilities/OnboardingTelemetryHelper.swift
  Blockzilla/metrics.yaml
  BlockzillaPackage/Sources/Onboarding/SwiftUI Onboarding/DefaultBrowserOnboardingView.swift
  BlockzillaPackage/Sources/Onboarding/SwiftUI Onboarding/GetStartedOnboardingView.swift
  BlockzillaPackage/Sources/Onboarding/SwiftUI Onboarding/OnboardingViewModel.swift
Labels: Needs Landing (Squash)

#3498 Fixes - #3494 The onboarding cards should be carousel style
  Blockzilla/Onboarding/OnboardingFactory.swift
  BlockzillaPackage/Sources/Onboarding/SwiftUI Onboarding/DefaultBrowserOnboardingView.swift
  BlockzillaPackage/Sources/Onboarding/SwiftUI Onboarding/GetStartedOnboardingView.swift
  BlockzillaPackage/Sources/Onboarding/SwiftUI Onboarding/OnboardingView.swift
  BlockzillaPackage/Sources/Onboarding/SwiftUI Onboarding/OnboardingViewModel.swift
Labels: Needs Landing (Squash)

#3502 Fixes #3474 The colors on the widget pop up are inconsistent
  BlockzillaPackage/Sources/Onboarding/DesignSystem/Color+AppColors.swift
  BlockzillaPackage/Sources/Onboarding/DesignSystem/Colors.xcassets/actionButton.colorset/Contents.json
  BlockzillaPackage/Sources/Onboarding/DesignSystem/Colors.xcassets/secondOnboardingScreenTopButton.colorset/Contents.json
  BlockzillaPackage/Sources/Onboarding/SwiftUI Onboarding/CardBannerView.swift
  BlockzillaPackage/Sources/Onboarding/SwiftUI Onboarding/DefaultBrowserOnboardingView.swift
  BlockzillaPackage/Sources/Onboarding/SwiftUI Onboarding/GetStartedOnboardingView.swift
Labels: Needs Landing (Squash)

#3506 Enable widgets
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/xcshareddata/xcschemes/FocusWidgetsExtension.xcscheme
  Blockzilla/UIComponents/UIConstants.swift
  BlockzillaPackage/Package.swift
  BlockzillaPackage/Sources/Onboarding/DesignSystem/Colors.xcassets/GradientFirst.colorset/Contents.json
  BlockzillaPackage/Sources/Onboarding/DesignSystem/Colors.xcassets/GradientSecond.colorset/Contents.json
  BlockzillaPackage/Sources/Onboarding/DesignSystem/Image+AppImages.swift
  BlockzillaPackage/Sources/Onboarding/SwiftUI Onboarding/CardBannerView.swift
  BlockzillaPackage/Sources/Onboarding/SwiftUI Onboarding/ShowMeHowOnboardingView.swift
  BlockzillaPackage/Sources/Widget/Assets.swift
  BlockzillaPackage/Sources/Widget/Media.xcassets/Contents.json
  BlockzillaPackage/Sources/Widget/Media.xcassets/GradientFirst.colorset/Contents.json
  BlockzillaPackage/Sources/Widget/Media.xcassets/GradientSecond.colorset/Contents.json
  BlockzillaPackage/Sources/Widget/Media.xcassets/icon_logo.imageset/Contents.json
  BlockzillaPackage/Sources/Widget/Media.xcassets/icon_logo.imageset/icon_logo.pdf
  BlockzillaPackage/Sources/Widget/SearchWidgetView.swift
  Widgets/Assets.xcassets/AccentColor.colorset/Contents.json
  Widgets/Assets.xcassets/AppIcon.appiconset/Contents.json
  Widgets/Assets.xcassets/Contents.json
  Widgets/Assets.xcassets/WidgetBackground.colorset/Contents.json
  Widgets/Info.plist
  Widgets/Widgets.swift
Labels: Needs Landing (Squash)

#3510 Version bump to 106.0
  Blockzilla/Info.plist
  ContentBlocker/Info.plist
  FocusIntentExtension/Info.plist
  OpenInFocus/Info.plist
Labels: Needs Landing

#3501 Upgrade Sentry to 7.27.1
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Landing

#3509 Change key for widget detail gallery
  Blockzilla/UIComponents/UIConstants.swift
Labels: Needs Landing (Squash)

#3512 Update string for translators better visibility
  Blockzilla/UIComponents/UIConstants.swift
Labels: Needs Landing (Squash)

#3520 Move strings to target to fix export
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/BrowserViewController.swift
  Blockzilla/UIComponents/UIConstants.swift
  Widgets/Widgets.swift
Labels: Needs Landing (Squash)

#3519 Update script to bump version number in Widgets
  Widgets/Info.plist
  tools/set-version.sh
Labels: Needs Landing (Squash)

#3524 Remove copyright string from widgets
  Blockzilla.xcodeproj/project.pbxproj
Labels: Needs Landing (Squash)

#3515 Enable old onboarding for beta testing
  Blockzilla/AppDelegate.swift
Labels: Needs Landing (Squash)

#3523 Fixes #2936 "Open Link" in page preview opens in external browser instead of Focus
  Blockzilla/BrowserViewController.swift
  Blockzilla/Menu/Protocol/MenuActionable.swift
  Blockzilla/Menu/Protocol/MenuItemProvider.swift
  Blockzilla/Modules/WebView/WebViewController.swift
Labels: Needs Landing (Squash)

#3507 For #3320 - Bitrise use pipelines
  .swiftlint.yml
  bitrise.yml
Labels: Needs Landing (Squash)

#3527 Fixes #3508 - On light mode asset is not visible and the text looks faded
  Blockzilla/Assets.xcassets/enabled-no.imageset/Contents.json
  Blockzilla/Assets.xcassets/enabled-no.imageset/enabled-no.pdf
  Blockzilla/Assets.xcassets/enabled-no.imageset/not-enabled-dark.pdf
  Blockzilla/Assets.xcassets/enabled-no.imageset/not-enabled-light.pdf
  Blockzilla/Assets.xcassets/instructions-cog.imageset/Contents.json
  Blockzilla/Assets.xcassets/instructions-cog.imageset/Instructions.pdf
  Blockzilla/Assets.xcassets/instructions-cog.imageset/instruction-settings-dark.pdf
  Blockzilla/Assets.xcassets/instructions-cog.imageset/instruction-settings-light.pdf
  Blockzilla/Assets.xcassets/instructions-cog.imageset/instructions-cog.pdf
  Blockzilla/Assets.xcassets/instructions-safari.imageset/Contents.json
  Blockzilla/Assets.xcassets/instructions-safari.imageset/Instructions Safari.pdf
  Blockzilla/Assets.xcassets/instructions-safari.imageset/instructions-safari.pdf
  Blockzilla/Assets.xcassets/instructions-safari.imageset/safari-instruction-dark.pdf
  Blockzilla/Assets.xcassets/instructions-safari.imageset/safari-instruction-light.pdf
  Blockzilla/Assets.xcassets/instructions-switch.imageset/Contents.json
  Blockzilla/Assets.xcassets/instructions-switch.imageset/dark-toggle.pdf
  Blockzilla/Assets.xcassets/instructions-switch.imageset/instructions-switch.pdf
  Blockzilla/Assets.xcassets/instructions-switch.imageset/light-toggle.pdf
  Blockzilla/Settings/Controller/SafariInstructionsViewController.swift
  Blockzilla/Settings/View/InstructionsView.swift
  Blockzilla/UIComponents/UIConstants.swift
  BlockzillaPackage/Sources/DesignSystem/Colors.xcassets/ExtensionNotEnabled.colorset/Contents.json
  BlockzillaPackage/Sources/DesignSystem/UIColor+AppColors.swift
  BlockzillaPackage/Sources/DesignSystem/UIFont+AppFonts.swift
  XCUITest/SettingAppearanceTest.swift
Labels: Needs Landing (Squash)

#3537 Fixes #3536 - Onboarding widget telemetry doesn't trigger the correct event
  Blockzilla/Utilities/OnboardingTelemetryHelper.swift
Labels: Needs Landing (Squash)

#3530 For #3529 - Bitrise pipelines for check ins in main
  bitrise.yml
Labels: Needs Landing (Squash)

#3533 Add Nimbus FML and first run experiments
  .experimenter.yaml
  .github/workflows/update-nimbus-experiments.yml
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/AppDelegate.swift
  Blockzilla/Info.plist
  Blockzilla/Nimbus/NimbusExtensions.swift
  Blockzilla/Nimbus/NimbusWrapper.swift
  Blockzilla/Nimbus/initial_experiments.json
  Blockzilla/Pro Tips/TipViewController.swift
  bin/nimbus-fml-configuration.sh
  bin/nimbus-fml.sh
  bitrise.yml
  nimbus.fml.yaml
Labels: Needs Landing (Squash)

#3540 Fixes #3531 Widget selection copy incorrect
  Widgets/Widgets.swift
Labels: Needs Landing (Squash)
