Repository mozilla-mobile/focus-ios, pull requests merged in 2022-01, with the labels that each got.

#2933 Fixes #2661 - Two shields icons are displayed
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#2942 Fixes #2931 - Leading margins are not the same, the text is not aligned
  Blockzilla/AutocompleteSettingViewController.swift
Labels: Needs Landing (Squash), Needs Uplift

#2943 Fixes #2939 - [iPad] The "Suggestion view" background is dismissed and the website shortcuts are visible in the page view
  Blockzilla/BrowserViewController.swift
  Blockzilla/ShortcutView.swift
Labels: Needs Landing (Squash), Needs Uplift

#2947 Fixes #2935 - The hamburger menu and shield icon are not correctly displayed in landscape when the URL bar is hidden
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash), Needs Uplift

#2957 Fixes #2953 - On landscape orientation, the textfield is not completely visible
  Blockzilla/SiriFavoriteViewController.swift
Labels: Needs Landing (Squash)

#2959 For #2958 - Bitrise upgrade xcode version
  XCUITest/PastenGoTest.swift
  bitrise.yml
Labels: Needs Landing (Squash)

#2955 For #2954 - XCUITests Fix and improve the l10n tests
  ScreenshotTests/BaseTestCaseL10n.swift
  ScreenshotTests/SnapshotTests.swift
Labels: Needs Landing

#2973 Fixes #2911 - First search’s suggestions are not tappable in landscape orientation
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#2964 Fixes #2901 - Implement Nimbus Internal Settings
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/AboutViewController.swift
  Blockzilla/InternalExperimentDetailView.swift
  Blockzilla/InternalExperimentsSettingsView.swift
  Blockzilla/InternalSettings.swift
  Blockzilla/InternalSettingsView.swift
  Blockzilla/NimbusExtensions.swift
  Blockzilla/NimbusWrapper.swift
  Blockzilla/SettingsViewController.swift
  Shared/Settings.swift
  bin/sdk_generator.sh
  bitrise.yml
Labels: Needs Landing (Squash), Needs Code Review

#2982 For #2981 - Fix flaky tests
  XCUITest/BasicBrowsing.swift
  XCUITest/SearchProviderTest.swift
  XCUITest/SettingAppearanceTest.swift
Labels: Needs Landing (Squash)

#2976 Fixes #2968 - The x button overlaps the etp toggle button when scrolling
  Blockzilla/Tracking Protection/TrackingProtectionViewController.swift
Labels: Needs Landing (Squash)

#2963 Pass build info to Glean initialize
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Blockzilla/AppDelegate.swift
  bin/sdk_generator.sh
Labels: Needs Landing (Squash)

#2998 For #2997 - XCUITests fix intermittent
  XCUITest/BaseTestCase.swift
  XCUITest/BasicBrowsing.swift
  XCUITest/OnboardingTest.swift
  XCUITest/SettingAppearanceTest.swift
  XCUITest/TPSidebarBadge.swift
Labels: Needs Landing (Squash)
