Repository mozilla-mobile/focus-ios, pull requests merged in 2022-02, with the labels that each got.

#3010 Fixes #3009 - Strings for Internal Settings should not be exported
  Blockzilla/InternalCrashReportingSettingsView.swift
  Blockzilla/InternalExperimentDetailView.swift
  Blockzilla/InternalExperimentsSettingsView.swift
  Blockzilla/InternalSettingsView.swift
Labels: Needs Landing (Squash)

#3014 Fixes #3012 - Add Glean debug settings to Internal Settings
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/AppDelegate.swift
  Blockzilla/InternalSettings.swift
  Blockzilla/InternalSettingsView.swift
  Blockzilla/InternalTelemetrySettingsView.swift
Labels: Needs Landing (Squash)

#3007 Fixes #2979 - Firefox Focus sometimes leaking browser content to app switcher screenshot
  Blockzilla/AppDelegate.swift
Labels: Needs Landing (Squash)

#3021 Update to A-S 91.0.0 and add direct Glean dependency (take 2)
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Landing (Squash)

#3035 Fixes #2999 Migrate Legacy Telemetry for Drag & Drop
  Blockzilla/BrowserViewController.swift
  Blockzilla/URLBar.swift
  Blockzilla/metrics.yaml
Labels: Needs Landing (Squash), Needs Code Review, Needs Data Review

#3031 Fixes #3003 Migrate Legacy Telemetry for Search Suggestions
  Blockzilla/OverlayView.swift
  Blockzilla/SearchSuggestionsPromptView.swift
  Blockzilla/SettingsViewController.swift
  Blockzilla/metrics.yaml
Labels: Needs Landing (Squash), Needs Code Review, Needs Data Review

#3040 Fixes #3000 Migrate Legacy Telemetry for Siri
  Blockzilla/AppDelegate.swift
  Blockzilla/metrics.yaml
Labels: Needs Landing (Squash), Needs Code Review, Needs Data Review

#3044 For #3043 - Add new team member as codeonwer
  .github/CODEOWNERS
Labels: Needs Landing

#3042 Add tooltip card component
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/Colors.xcassets/Purple30.colorset/Contents.json
  Blockzilla/Colors.xcassets/Purple70.colorset/Contents.json
  Blockzilla/Extensions/UIImage+AppImages.swift
  Blockzilla/TooltipView.swift
  Blockzilla/UIColorExtensions.swift
Labels: Needs Landing (Squash)

#3041 Fixes #3011 - Add logic for onboarding functionality
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/AppDelegate.swift
  Blockzilla/BrowserToolset.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/IntroViewController.swift
  Blockzilla/Onboarding/NewOnboardingReplaceViewController.swift
  Blockzilla/Onboarding/OnboardingConstants.swift
  Blockzilla/Onboarding/OnboardingEventsHandler.swift
  Blockzilla/Onboarding/WhatsNewEventsHandler.swift
  Blockzilla/Tracking Protection/TrackingProtectionDelegate.swift
  Blockzilla/Tracking Protection/TrackingProtectionViewController.swift
  XCUITest/OnboardingTest.swift
Labels: Needs Landing (Squash)

#3047 Remove tooltip view
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/TooltipView.swift
Labels: Needs Landing (Squash)

#3039 Fixes #3023 Implement Onboarding first screen UI
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/Assets.xcassets/icon_history.imageset/Contents.json
  Blockzilla/Assets.xcassets/icon_history.imageset/History-1.pdf
  Blockzilla/Assets.xcassets/icon_history.imageset/History.pdf
  Blockzilla/Assets.xcassets/icon_mozilla.imageset/Contents.json
  Blockzilla/Assets.xcassets/icon_mozilla.imageset/Fox - Light Theme 2.2.pdf
  Blockzilla/Assets.xcassets/icon_private_mode.imageset/Contents.json
  Blockzilla/Assets.xcassets/icon_private_mode.imageset/Private mode-24.pdf
  Blockzilla/Assets.xcassets/icon_private_mode.imageset/Private mode.pdf
  Blockzilla/Colors.xcassets/PrimaryButton.colorset/Contents.json
  Blockzilla/OnboardingViewController.swift
  Blockzilla/UIColorExtensions.swift
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#3048 Fixes #2994 Allow shortcuts to be renamed
  Blockzilla/Assets.xcassets/edit.imageset/Contents.json
  Blockzilla/Assets.xcassets/edit.imageset/Edit-dark.pdf
  Blockzilla/Assets.xcassets/edit.imageset/Edit.pdf
  Blockzilla/BrowserViewController.swift
  Blockzilla/Extensions/UIImage+AppImages.swift
  Blockzilla/ShortcutView.swift
  Blockzilla/ShortcutsManager.swift
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#3049 Fixes #2989 Implement Onboarding Screen
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/AppDelegate.swift
  Blockzilla/Onboarding/NewOnboardingReplaceViewController.swift
  Blockzilla/Onboarding/OnboardingViewController.swift
Labels: Needs Landing (Squash)

#3050 Fixes #2990 Implement Shield Tooltip
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/Assets.xcassets/icon_close.imageset/Contents.json
  Blockzilla/Assets.xcassets/icon_close.imageset/FILL.pdf
  Blockzilla/BrowserViewController.swift
  Blockzilla/Extensions/UIImage+AppImages.swift
  Blockzilla/TooltipView.swift
  Blockzilla/TooltipViewController.swift
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#3051 Fixes #3005 - Remove the home screen tips
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/AppDelegate.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/HomeViewController.swift
  Blockzilla/InternalOnboardingSettingsView.swift
  Blockzilla/InternalSettings.swift
  Blockzilla/InternalSettingsView.swift
  Blockzilla/Onboarding/OnboardingConstants.swift
  Blockzilla/Onboarding/OnboardingEventsHandler.swift
  Blockzilla/Onboarding/WhatsNewEventsHandler.swift
  Blockzilla/SettingsViewController.swift
Labels: Needs Landing (Squash)

#3033 For #3032 - Bitrise create test workflow
  bitrise.yml
Labels: Needs Landing (Squash)

#3038 For #3037 - Add unit tests to bitrise
  Blockzilla.xcodeproj/UnitTests.xctestplan
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/xcshareddata/xcschemes/Focus.xcscheme
  Blockzilla.xcodeproj/xcshareddata/xcschemes/Klar.xcscheme
  XCUITest/BasicBrowsing.swift
  XCUITest/PastenGoTest.swift
  XCUITest/SettingAppearanceTest.swift
  bitrise.yml
Labels: Needs Landing (Squash)

#3052 Fixes #2992 - Implement the Hamburger Menu Tooltip
  Blockzilla/BrowserViewController.swift
  Blockzilla/TooltipView.swift
  Blockzilla/TooltipViewController.swift
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#3060 Fixes #2991 - Implement Trash Button Tooltip
  Blockzilla/BrowserToolbar.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/UIConstants.swift
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#3062 Fixes #3059 - Menu ToolTip should appear on home screen at startup of the app
  Blockzilla/AppDelegate.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/Onboarding/OnboardingEventsHandler.swift
Labels: Needs Landing (Squash)
