Repository mozilla-mobile/focus-ios, pull requests merged in 2022-03, with the labels that each got.

#3063 Fixes #2993 implement the (in line) settings tooltip
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/Declarative DataSource/DataSource.swift
  Blockzilla/Declarative DataSource/Section.swift
  Blockzilla/Declarative DataSource/SectionItem.swift
  Blockzilla/Onboarding/TooltipTableViewCell.swift
  Blockzilla/TooltipView.swift
  Blockzilla/Tracking Protection/TrackingProtectionViewController.swift
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#3046 For #3045 - Bitrise fix l10nBuild workflow
  ScreenshotTests/SnapshotHelper.swift
  bitrise.yml
Labels: Needs Landing (Squash)

#3057 For #3056 - remove 'mozilla-mobile/releng' as CODEOWNER of bitrise.yml
  .github/CODEOWNERS
Labels: Needs Landing (Squash)

#3072 Fixes #3071 - Implement a staging experiment for testing new vs old onboarding
  Blockzilla/InternalOnboardingSettingsView.swift
  Blockzilla/InternalSettings.swift
  Blockzilla/NimbusWrapper.swift
  Blockzilla/Onboarding/OnboardingEventsHandler.swift
Labels: Needs Landing (Squash)

#3068 Fixes #3061 - Tools options (nav arrow, trash button, hamburger menu) don't appear when rotating the device in circle after reaching second landscape mode
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#3085 fix l10nScreenshots tests for each locale
  ScreenshotTests/SnapshotHelper.swift
Labels: Needs Landing (Squash)

#3101 Fixes #3096 - Context Menu disappears after dismissing the keyboard, then rotating landscape, then portrait
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#3102 Fixes #2988 Onboarding refresh
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/AppDelegate.swift
  Blockzilla/Assets.xcassets/icon_close.imageset/Contents.json
  Blockzilla/Assets.xcassets/icon_close.imageset/FILL.pdf
  Blockzilla/Assets.xcassets/icon_history.imageset/Contents.json
  Blockzilla/Assets.xcassets/icon_history.imageset/History-1.pdf
  Blockzilla/Assets.xcassets/icon_history.imageset/History.pdf
  Blockzilla/Assets.xcassets/icon_mozilla.imageset/Contents.json
  Blockzilla/Assets.xcassets/icon_mozilla.imageset/Fox - Light Theme 2.2.pdf
  Blockzilla/Assets.xcassets/icon_private_mode.imageset/Contents.json
  Blockzilla/Assets.xcassets/icon_private_mode.imageset/Private mode-24.pdf
  Blockzilla/Assets.xcassets/icon_private_mode.imageset/Private mode.pdf
  Blockzilla/BrowserToolbar.swift
  Blockzilla/BrowserToolset.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/Colors.xcassets/PrimaryButton.colorset/Contents.json
  Blockzilla/Declarative DataSource/DataSource.swift
  Blockzilla/Declarative DataSource/Section.swift
  Blockzilla/Declarative DataSource/SectionItem.swift
  Blockzilla/Extensions/UIImage+AppImages.swift
  Blockzilla/HomeViewController.swift
  Blockzilla/InternalOnboardingSettingsView.swift
  Blockzilla/InternalSettings.swift
  Blockzilla/InternalSettingsView.swift
  Blockzilla/IntroViewController.swift
  Blockzilla/NimbusWrapper.swift
  Blockzilla/Onboarding/OnboardingConstants.swift
  Blockzilla/Onboarding/OnboardingEventsHandler.swift
  Blockzilla/Onboarding/OnboardingViewController.swift
  Blockzilla/Onboarding/TooltipTableViewCell.swift
  Blockzilla/Onboarding/WhatsNewEventsHandler.swift
  Blockzilla/SettingsViewController.swift
  Blockzilla/TooltipView.swift
  Blockzilla/TooltipViewController.swift
  Blockzilla/Tracking Protection/TrackingProtectionDelegate.swift
  Blockzilla/Tracking Protection/TrackingProtectionViewController.swift
  Blockzilla/UIColorExtensions.swift
  Blockzilla/UIConstants.swift
  Blockzilla/URLBar.swift
  XCUITest/OnboardingTest.swift
Labels: Needs Landing (Squash)

#3109 Fixes #2994 Allow shortcuts to be renamed
  Blockzilla/ShortcutView.swift
Labels: Needs Landing (Squash)

#3110 Fixes 3088 - The onboarding icon size is not the same (PB, History, and settings)
  Blockzilla/Assets.xcassets/icon_history.imageset/Contents.json
  Blockzilla/Assets.xcassets/icon_history.imageset/History-24.pdf
  Blockzilla/Assets.xcassets/icon_history.imageset/History-25.pdf
  Blockzilla/Assets.xcassets/icon_private_mode.imageset/Contents.json
  Blockzilla/Assets.xcassets/icon_private_mode.imageset/Private Mode-25.pdf
  Blockzilla/Assets.xcassets/icon_private_mode.imageset/Private mode.pdf
  Blockzilla/Onboarding/OnboardingViewController.swift
Labels: Needs Landing (Squash)

#3111 Fixes #3091 - The ETP tooltip is not centered on the shield icon
  Blockzilla/UIConstants.swift
Labels: Needs Landing (Squash)

#3112 Fixes #3090 - The settings tooltip is not centered to the hamburger menu
  Blockzilla/BrowserToolset.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/UIConstants.swift
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#3075 Fixes #3064 Use biometric authentication at the start of the app
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/AppDelegate.swift
  Blockzilla/AuthenticationManager.swift
  Blockzilla/BrowserViewController.swift
  Blockzilla/Extensions/UIButton+Background.swift
  Blockzilla/Extensions/UIImage+AppImages.swift
  Blockzilla/Menu/Protocol/MenuItemProvider.swift
  Blockzilla/SettingsViewController.swift
  Blockzilla/SplashView.swift
  Blockzilla/Tracking Protection/TrackingProtectionDelegate.swift
  Blockzilla/Tracking Protection/TrackingProtectionViewController.swift
  ClientTests/BrowserViewControllerTests.swift
Labels: Needs Landing (Squash)

#3116 Fixes #3114 - The PB icon on the new onboarding card is way too dark
  Blockzilla/Assets.xcassets/icon_private_mode.imageset/Contents.json
Labels: Needs Landing (Squash)

#3120 Fixes #3115 - The Trash icon tooltip re-appears when rotating the device from landscape to portrait or vice versa
  Blockzilla/TooltipViewController.swift
Labels: Needs Landing (Squash)

#3125 Resize ETP-Off ImageView and Site-Not-Secure ImageView to the same size as ETP-On ImageView
  Blockzilla/UIConstants.swift
  Blockzilla/URLBar.swift
Labels: Needs Landing (Squash)

#3126 Fixes #3098 ETP menu bounce when opening it if ETP is turned OFF
  Blockzilla/Tracking Protection/Presentation/SheetMetrics.swift
  Blockzilla/Tracking Protection/Presentation/SheetModalViewController.swift
Labels: Needs Landing (Squash)

#3130 Fixes #3099 The Tracking Protection state (on or off) is reset if restarting the app or deleting the history
  Blockzilla/BrowserViewController.swift
  Blockzilla/Lib/TrackingProtection/TrackingProtection.swift
  Blockzilla/Modules/WebView/WebViewController.swift
Labels: Needs Landing (Squash)

#3136 Fixes #3122 - The Hamburger menu tooltip is not displayed if restarting Focus before pressing Start Browsing
  Blockzilla/Onboarding/OnboardingEventsHandler.swift
Labels: Needs Landing (Squash)

#3137 Fixes #2862 - The page added as favorite site is opened but the website shortcuts are displayed while the page is in view.
  Blockzilla/Assets.xcassets/icon_private_mode.imageset/Contents.json
  Blockzilla/BrowserViewController.swift
  Blockzilla/ShortcutsManager.swift
  Blockzilla/Tracking Protection/TrackingProtectionViewController.swift
Labels: Needs Landing (Squash)

#3139 Fixes #3124 - The Save button is not grayed out when no text is entered in the shortcut name box (when renaming a shortcut)
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#3146 Fixes #3114 - The PB icon on the new onboarding card is way too dark
  Blockzilla/Assets.xcassets/icon_private_mode.imageset/Contents.json
  Blockzilla/Assets.xcassets/icon_private_mode.imageset/icon_private_mode.pdf
  Blockzilla/Assets.xcassets/icon_private_mode.imageset/icon_private_mode_dark.pdf
Labels: Needs Landing (Squash)

#3147 Fixes #3145 Removing a shortcut doesn't redirect the user to the URL bar and the keyboard is not opened
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#3129 Fixes #3128 - Bootstrap Taskgraph from pypi in decision task
  .taskcluster.yml
  taskcluster/focusios_taskgraph/__init__.py
  taskcluster/focusios_taskgraph/job.py
  taskcluster/focusios_taskgraph/loader/screenshots_locales.py
  taskcluster/focusios_taskgraph/util/chunkify.py
  taskcluster/requirements.in
  taskcluster/requirements.txt
Labels: eng:automation, Needs Landing (Squash)

#3151 Fixes #3128 - Fix Python 3 compatibility error in taskgraph
  taskcluster/focusios_taskgraph/target_tasks.py
Labels: eng:automation, Needs Landing

#3118 For #3117 - Upgrade to xcode 13.3 if app builds successfully
  bitrise.yml
Labels: Needs Landing

#3156 Fixes #3155 - The name of the shortcut overlaps with another one
  Blockzilla/AppShortcuts/ShortcutView.swift
Labels: Needs Landing (Squash)
