Repository mozilla-mobile/focus-ios, pull requests merged in 2022-07, with the labels that each got.

#3323 Fixes #3311 - The scrim size is smaller than the screen
  Blockzilla/BrowserViewController.swift
  Blockzilla/HomeViewController.swift
Labels: Needs Landing (Squash)

#3327 For #3326 - XCUITest update Smoketest plan
  SmokeTest.xctestplan
Labels: Needs Landing (Squash)

#3341 Add template header
  Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/IDETemplateMacros.plist
  Blockzilla.xcodeproj/xcshareddata/IDETemplateMacros.plist
Labels: Needs Landing (Squash)

#3344 Fixes #3328 Add toggle to set Focus as default browser within Focus settings
  Blockzilla/Settings/Controller/SettingsViewController.swift
  Blockzilla/UIComponents/UIConstants.swift
  Blockzilla/metrics.yaml
Labels: Needs Landing (Squash), Needs Data Review

#3349 Fixes #3348 Remove SnapKit from Packages
  BlockzillaPackage/Package.swift
  BlockzillaPackage/Sources/UIHelpers/UIButton+Background.swift
  BlockzillaPackage/Sources/UIHelpers/UIViewController+Child.swift
Labels: Needs Landing (Squash)

#3353 Fixes 3352 - String related to AppName for set as default browser description should be added dynamically
  Blockzilla/Settings/Controller/SettingsViewController.swift
  Blockzilla/UIComponents/UIConstants.swift
Labels: Needs Landing (Squash)

#3354 Replace 3 dots with ellipsis in string
  Blockzilla/en.lproj/Localizable.strings
Labels: Needs Landing (Squash)

#3303 Submit commits to Glean probe-scraper
  .github/workflows/glean-probe-scraper.yml
Labels: Needs Landing
