Repository mozilla-mobile/focus-ios, pull requests merged in 2022-09, with the labels that each got.

#3423 Fixes #3393 Update the trash can CFR
  Blockzilla/BrowserViewController.swift
  Blockzilla/UIComponents/UIConstants.swift
  BlockzillaPackage/Sources/Onboarding/OnboardingEventsHandler.swift
Labels: Needs Landing (Squash)

#3430 Fixes #3351 Create a search widget
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/xcshareddata/xcschemes/ContentBlocker.xcscheme
  Blockzilla.xcodeproj/xcshareddata/xcschemes/FocusIntentExtension.xcscheme
  Blockzilla.xcodeproj/xcshareddata/xcschemes/FocusWidgetsExtension.xcscheme
  Blockzilla.xcodeproj/xcshareddata/xcschemes/ShareExtension.xcscheme
  Blockzilla/UIComponents/UIConstants.swift
  FocusWidgets/Assets.xcassets/Colors/Contents.json
  FocusWidgets/Assets.xcassets/Colors/GradientFirst.colorset/Contents.json
  FocusWidgets/Assets.xcassets/Colors/GradientSecond.colorset/Contents.json
  FocusWidgets/Assets.xcassets/Contents.json
  FocusWidgets/Assets.xcassets/Images/Contents.json
  FocusWidgets/Assets.xcassets/Images/icon_mozilla.imageset/Contents.json
  FocusWidgets/Assets.xcassets/Images/icon_mozilla.imageset/Fox - Light Theme 2.2.pdf
  FocusWidgets/Assets.xcassets/WidgetBackground.colorset/Contents.json
  FocusWidgets/FocusWidgets.swift
  FocusWidgets/Info.plist
  FocusWidgets/SearchWidgetView.swift
Labels: Needs Landing (Squash)

#3367 Fixes #3330-Search-Telemetry-addition
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla/Ads.js
  Blockzilla/Modules/WebView/WebViewController.swift
  Blockzilla/Utilities/AdsTelemetryHelper.swift
  Blockzilla/metrics.yaml
  ClientTests/TrackingAdsTests.swift
Labels: Needs Landing (Squash), Needs Data Review

#3441 Refactor FXIOS [v106] Screenshot Tests
  ScreenshotTests/BaseTestCaseL10n.swift
  ScreenshotTests/SnapshotTests.swift
Labels: Needs Landing

#3437 #3433 Error when building the app: FocusWidgetsExtension has conflicting provisioning settings
  Blockzilla.xcodeproj/project.pbxproj
Labels: Needs Landing (Squash)

#3443 Fix obsolete content in en.lproj/Localizable.strings
  Blockzilla/en.lproj/Localizable.strings
Labels: Needs Landing (Squash)

#3446 Add spaces around dashes in TooltipBodyText.TrashIcon.V2
  Blockzilla/UIComponents/UIConstants.swift
Labels: Needs Landing (Squash)

#3452 Fix Xcode 14 RC compile issue
  OpenInFocus/ActionViewController.swift
  bitrise.yml
Labels: Needs Landing (Squash)

#3447 L10n tests a few more updates
  ScreenshotTests/BaseTestCaseL10n.swift
  ScreenshotTests/SnapshotTests.swift
Labels: Needs Landing (Squash)

#3448 Upgrade to Glean v51.2.0
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  bin/sdk_generator.sh
Labels: Needs Landing (Squash)

#3459 Fix #3458 - Set less frequency for import-strings job
  .github/workflows/import-strings.yml
Labels: Needs Landing

#3463 Fallback to original strings for 105
  Blockzilla/BrowserViewController.swift
Labels: Needs Landing (Squash)

#3477 Fix strings
  Blockzilla/Onboarding/OnboardingFactory.swift
Labels: Needs Landing (Squash)

#3470 Fixes-3453-Remove snapkit from HomeViewController
  Blockzilla/HomeViewController.swift
Labels: Needs Landing (Squash)

#3465 Fixes #3425 - Telemetry counting the number of times the app is opened from an external link
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Blockzilla/AppDelegate.swift
  Blockzilla/Extensions/URLExtensions.swift
  Blockzilla/NavigationPath.swift
  Blockzilla/metrics.yaml
  ClientTests/NavigationPathTests.swift
Labels: Needs Landing (Squash)

#3480 Fixes #3469 - The "Get Started" button is not fully displayed in landscape mode
  Blockzilla/Onboarding/OnboardingFactory.swift
  BlockzillaPackage/Sources/Onboarding/OnboardingHostingControllerV2.swift
  BlockzillaPackage/Sources/Onboarding/SwiftUI Onboarding/DefaultBrowserOnboardingView.swift
Labels: Needs Landing (Squash)

#3481 Explain placeholder
  Blockzilla/Onboarding/OnboardingFactory.swift
Labels: Needs Landing (Squash)

#3482 Fixes #3472 The text is not fully displayed on the widget addition pop-up
  BlockzillaPackage/Sources/Onboarding/SwiftUI Onboarding/CardBannerView.swift
Labels: Needs Landing (Squash)

#3484 Fixes #3472 The text is not fully displayed on the widget addition pop up
  Blockzilla/BrowserViewController.swift
  Blockzilla/Onboarding/OnboardingFactory.swift
  BlockzillaPackage/Sources/Onboarding/PortraitHostingController.swift
  BlockzillaPackage/Sources/Onboarding/SwiftUI Onboarding/ShowMeHowOnboardingView.swift
Labels: Needs Landing (Squash)

#3483 Fixes #3479 Browser search count telemetry addition
  Blockzilla/BrowserViewController.swift
  Blockzilla/metrics.yaml
Labels: Needs Landing (Squash)

#3485 Run import-strings on Sunday instead of Monday
  .github/workflows/import-strings.yml
Labels: Needs Landing (Squash)

#3491 Skip localization for internal menu
  Blockzilla/InternalSettings/InternalOnboardingSettingsView.swift
Labels: Needs Landing (Squash)

#3493 Show internal menu for onboarding on release
  Blockzilla/InternalSettings/InternalSettingsView.swift
Labels: Needs Landing (Squash)
