Repository mozilla-mobile/focus-ios, pull requests merged in 2023-06, with the labels that each got.

#3770 Update base image of screenshots Dockerfile
  taskcluster/docker/screenshots/Dockerfile
Labels: Needs Landing (Squash)

#3771 ci: switch screenshots tasks to GCP
  taskcluster/ci/config.yml
Labels: Needs Landing

#3765 Call out that the `main` branch is tested on Xcode 14
  README.md
Labels: Needs Landing

#3784 Update Glean to v53.0.0
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  bin/sdk_generator.sh
Labels: Needs Landing

#3798 Add newer style parameters for NimbusBuilder
  Blockzilla/Nimbus/NimbusWrapper.swift
Labels: Needs Landing

#3796 Update Sentry to version 8.8.0
  Blockzilla.xcodeproj/project.pbxproj
  Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Landing, Needs Code Review
