Repository mozilla-mobile/focus-ios, pull requests merged in 2023-12, with the labels that each got.

#3932 Update Sentry to version 8.17.1
  focus-ios/Blockzilla.xcodeproj/project.pbxproj
  focus-ios/Blockzilla.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Needs Landing (Squash), Needs Code Review

#3949 Fix url encoding
  focus-ios/Blockzilla/Utilities/URIFixup.swift
  focus-ios/focus-ios-tests/ClientTests/URIFixupTests.swift
Labels: Needs Landing (Squash)

#3956 Fix MTE-2022 testSearchQuery test
  focus-ios/focus-ios-tests/XCUITest/SearchProviderTest.swift
Labels: Needs Landing

#3962 Move to new directory before bootstrapping nimbus-fml.sh
  checkout.sh
  focus-ios/.gitignore
  focus-ios/bin/nimbus-fml.sh
Labels: Needs Landing
